/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFCliente.java
 *
 * Created on 8/Out/2011, 22:38:32
 */

package br.classesprincipais;
import br.utilitario.Conexao;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import br.utilitario.Util;
import java.awt.Color;
import java.awt.Component;
import java.util.Locale;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author M4RCO5
 */
public class JFCliente extends javax.swing.JFrame {

    /** Creates new form JFCliente */
    Conexao con = new Conexao();
    private String nomeselecionado="";
    private int alterar=1;
    private String ordem="nome_cliente";
    private String sexo = "M";
    int inicia=0;
    private int indiceComboUltimo=0;
    private int indiceCombo=0;
     
    public JFCliente() throws ParseException {
        initComponents();
        atualizaClientes();
        atualizaCidades();
        preenchejTable("");
        //jCcidade.addItem("aljas");
        //jCcidade.addItem("rrrrrrrras");


        setLocationRelativeTo(null);
        jTcodigo.setEditable(false);
        jTcidade.setEditable(false);
       
        
    }
 
    public JFCliente(String codigo)
    {
        initComponents();
        atualizaClientes();
        atualizaCidades();
        preenchejTable("");

        setLocationRelativeTo(null);
        jTcodigo.setEditable(false);
        jTcidade.setEditable(false);
   
        try
        {
            con.conecta();
            con.executeStatement("select * from cliente where codCliente = "+codigo);
            con.getRs().next();
            mostraDados();

            con.conecta();
            con.executeStatement("select * from cidade where codCidade  = "+jTcidade.getText());
            con.getRs().next();
            jCcidade.setSelectedItem(con.getRs().getString("nome_cidade"));
        }catch(Exception e)
        {
             javax.swing.JOptionPane.showMessageDialog(null,e);
        }
        

    }
    
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTtel = new javax.swing.JTextField();
        jTendereco = new javax.swing.JTextField();
        jTcpf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCcliente = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTcidade = new javax.swing.JTextField();
        jCcidade = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jRm = new javax.swing.JRadioButton();
        jRf = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTpesquisaTable = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de clientes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));
        jPanel1.add(jTnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 520, -1));

        jLabel2.setText("CPF :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel3.setText("Telefone : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setText("Endereço :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jTtel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTtelKeyPressed(evt);
            }
        });
        jPanel1.add(jTtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 200, -1));
        jPanel1.add(jTendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 650, -1));

        jTcpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTcpfKeyPressed(evt);
            }
        });
        jPanel1.add(jTcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 160, -1));

        jLabel5.setText("Todos clientes");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, -1, -1));

        jCcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCclienteActionPerformed(evt);
            }
        });
        jPanel1.add(jCcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 600, -1));

        jLabel6.setText("Código :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTcodigo.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jTcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 71, -1));

        jLabel7.setText("Cidade :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jTcidade.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jTcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 60, -1));

        jCcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcidadeActionPerformed(evt);
            }
        });
        jPanel1.add(jCcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 580, -1));

        jLabel8.setText("Sexo :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        buttonGroup1.add(jRm);
        jRm.setSelected(true);
        jRm.setText("M");
        jRm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRmActionPerformed(evt);
            }
        });
        jPanel1.add(jRm, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        buttonGroup1.add(jRf);
        jRf.setText("F");
        jRf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRfActionPerformed(evt);
            }
        });
        jPanel1.add(jRf, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 730, 14));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Telefone", "CPF", "Cidade", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
        jTable1.setRowHeight(22);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 710, 250));

        jLabel9.setText("Pesquisar na tabela.:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jTpesquisaTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTpesquisaTableKeyReleased(evt);
            }
        });
        jPanel1.add(jTpesquisaTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 300, -1));

        jButton10.setText("Pesquisar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 120, -1));

        jButton11.setText("Exibir todos");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 140, -1));

        jButton6.setText("<<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 90, -1));

        jButton7.setText("<");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 90, -1));

        jButton8.setText(">");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 90, -1));

        jButton9.setText(">>");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 90, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/city-icon.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, 100, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/porta.gif"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 100, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/delete2.JPG"))); // NOI18N
        jButton2.setToolTipText("Deletar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, 100, 41));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/Split.png"))); // NOI18N
        jButton4.setToolTipText("Novo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 100, 41));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/Save.png"))); // NOI18N
        jButton1.setToolTipText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 100, 41));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 720, 10));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Código");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 80, -1));

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Nome");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 110, -1));

        jLabel10.setText("Ordenação.:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 710, 10));

        jMenu1.setText("Sistema");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
           /*caso nao tenha clicado no botao novo, 
            o valor da variavel alterar, estará em 0*/
           if(alterar==1)
           {

               if((verificaNome(jTnome.getText())!=true) || (jTnome.getText().equalsIgnoreCase(nomeselecionado)))
               {
                   con.conecta();
                   con.executaSql("update  cliente set nome_cliente='"+jTnome.getText()+"',"
                           + "telefone='"+jTtel.getText()+"', cpf='"+jTcpf.getText()+"', endereco='"+jTendereco.getText()+"',"
                           + "sexo='"+sexo+"',cidade_codCidade="+jTcidade.getText()+
                           " where codCliente = "+jTcodigo.getText());
                   con.getPs().execute();

                   atualizaClientes() ;
                   preenchejTable("");
                   javax.swing.JOptionPane.showMessageDialog(null,"Alterado com sucesso");
                   alterar=1;
                   preenchejTable("");
                   
               }else
               {
                   jTnome.setText(nomeselecionado);
                   JOptionPane.showMessageDialog(null,"Este cliente ja está cadastrado !");
               }
               
           }else if(verificaNome(jTnome.getText())==true)
           {
               JOptionPane.showMessageDialog(null,"Este cliente ja está cadastrado !");
           }else
           {
               con.conecta();
               con.executaSql("insert into cliente(nome_cliente,telefone,cpf,endereco,sexo,cidade_codCidade,qtde_comprado) values(?,?,?,?,?,?,?)");
               con.getPs().setString(1,jTnome.getText());
               con.getPs().setString(2,jTtel.getText());
               con.getPs().setString(3,jTcpf.getText());
               con.getPs().setString(4,jTendereco.getText());
               con.getPs().setString(5,sexo);
               con.getPs().setString(6,jTcidade.getText());
               con.getPs().setString(7,"0");
               con.getPs().execute();

               atualizaClientes() ;
               preenchejTable("");
               javax.swing.JOptionPane.showMessageDialog(null,"Salvo com sucesso");
               //limpaCampos();
               alterar=1;
           }

        } catch (Exception ex) {
             JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCclienteActionPerformed

    // if(inicia==1)
   //  {
        try
       {
           con.conecta();
           boolean achei =false;
           con.executeStatement("select * from cliente order by "+ordem);
           con.getRs().first();
           while(achei==false)
           {
               if(con.getRs().getString("nome_cliente").equals(jCcliente.getSelectedItem()))
               {
                   achei = true;
               }else
               {
                   con.getRs().next();
               }
           }

           mostraDados();
          

       }catch(Exception e)
       {
         //  javax.swing.JOptionPane.showMessageDialog(null, e);
       }

     //}

     inicia=1;
    }//GEN-LAST:event_jCclienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       JFlogin login = new JFlogin();
       Util util = new Util();
       try
       {
           if(util.confirmaAdministrador(login.retornaUsuario()))
           {
               con.conecta();

               int i = JOptionPane.showConfirmDialog(null,"Deseja excluir o cliente : "+jTnome.getText()+" ? ");
               if(i==0)
               {
                  con.executaSql("delete from cliente where codCliente = "+jTcodigo.getText());
                  con.getPs().execute();

                  atualizaClientes();
                  preenchejTable("");
                  javax.swing.JOptionPane.showMessageDialog(null, "Excluido com sucesso");

               }
               
           }else
           {
               javax.swing.JOptionPane.showMessageDialog(null, "Este usuário não tem permissão para esta operação!");
           }
           
           
       }catch(Exception e)
       {
           javax.swing.JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcidadeActionPerformed
 try
       {
           con.conecta();
           boolean achei =false;
           con.executeStatement("select * from cidade order by nome_cidade ");
           con.getRs().first();
           while(achei==false)
           {
               if(con.getRs().getString("nome_cidade").equals(jCcidade.getSelectedItem()))
               {
                   achei = true;
               }else
               {
                   con.getRs().next();
               }
           }

           jTcidade.setText(con.getRs().getString("codCidade"));
          

       }catch(Exception e)
       {
         //  javax.swing.JOptionPane.showMessageDialog(null, e);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jCcidadeActionPerformed

    private void jRmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRmActionPerformed
       sexo ="M";
    }//GEN-LAST:event_jRmActionPerformed

    private void jRfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRfActionPerformed
       sexo="F";
    }//GEN-LAST:event_jRfActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        alterar=0;
        limpaCampos();
       try
       {
           int codigo =0;
           con.conecta();
           con.executaSql("select max(codCliente) from cliente");
           con.getRs().next();
           
           codigo = Integer.parseInt(con.getRs().getString("max(codCliente)"));
           
           jTcodigo.setText(String.valueOf(codigo+1));
           
           jCcidade.setSelectedItem("Muriae");
           
       }catch(Exception e)
       {
           //JOptionPane.showMessageDialog(null, e);
       }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JFCadastros aux = new JFCadastros();
        aux.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        con.fechaConexao();
    }//GEN-LAST:event_formWindowClosing

    private void jTcpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcpfKeyPressed
        String t ="";
        
        t = jTcpf.getText();
        if(t.length()==3)
        {
            jTcpf.setText(jTcpf.getText()+".");
        }
        
        t = jTcpf.getText();
        
        if(t.length()==7)
        {
            jTcpf.setText(jTcpf.getText()+".");
        }
        
        t = jTcpf.getText();
        
        if(t.length()==11)
        {
            jTcpf.setText(jTcpf.getText()+"-");
        }
        
        if(jTcpf.getText().length() ==13)
        {
            jCcidade.grabFocus();
            
        }
    }//GEN-LAST:event_jTcpfKeyPressed

    private void jTtelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtelKeyPressed
               String t ="";
        
        t = jTtel.getText();
        if(t.length()==4)
        {
            jTtel.setText(jTtel.getText()+"-");
        }

        
        if(jTtel.getText().length() ==9)
        {
            jCcidade.grabFocus();
            
        }
    }//GEN-LAST:event_jTtelKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jCcliente.setSelectedItem(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1)));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
     if(indiceCombo==indiceComboUltimo-1)
        {
            JOptionPane.showMessageDialog(null,"Este é o ultimo registro");
        }else
        {
            System.out.println("ultimo:  "+(indiceComboUltimo-1));
            jCcliente.setSelectedIndex(indiceCombo+1);
            indiceCombo = jCcliente.getSelectedIndex();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jCcliente.setSelectedIndex(0);
       indiceCombo = jCcliente.getSelectedIndex();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
          if(indiceCombo==0)
        {
            JOptionPane.showMessageDialog(null,"Este é o primeiro registro");
        }else
        {
            jCcliente.setSelectedIndex(indiceCombo-1);
            indiceCombo = jCcliente.getSelectedIndex();
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jCcliente.setSelectedIndex(indiceComboUltimo-1);
        indiceCombo = jCcliente.getSelectedIndex();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       preenchejTable(jTpesquisaTable.getText());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
         preenchejTable("");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
      ordem = "codCliente";
      preenchejTable("");
      atualizaClientes();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        ordem = "nome_cliente";
      preenchejTable("");
      atualizaClientes();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTpesquisaTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpesquisaTableKeyReleased
        preenchejTable(jTpesquisaTable.getText());
    }//GEN-LAST:event_jTpesquisaTableKeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFCliente().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(JFCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jCcidade;
    private javax.swing.JComboBox jCcliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRf;
    private javax.swing.JRadioButton jRm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTcidade;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTcpf;
    private javax.swing.JTextField jTendereco;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTpesquisaTable;
    private javax.swing.JTextField jTtel;
    // End of variables declaration//GEN-END:variables
public boolean verificaNome(String nome) throws Exception {  
    boolean achou = false;  
    String sql = "select nome_cliente from cliente";  
    con.conecta();
    con.executaSql(sql);     
    while (!achou  && con.getRs().next()) {  
        if (nome.equalsIgnoreCase(con.getRs().getString("nome_cliente"))) {  
            achou = true;  
        }  
    }  
    con.getRs().close();  
    con.getPs().close();  
    return achou;  
}  
     
    private void mostraDados()
    {
        try
        {

            jTcpf.setText(con.getRs().getString("cpf"));
            jTendereco.setText(con.getRs().getString("endereco"));
            jTnome.setText(con.getRs().getString("nome_cliente"));
            jTtel.setText(con.getRs().getString("telefone"));
            jTcodigo.setText(con.getRs().getString("codCliente"));
            nomeselecionado = jTnome.getText();
            if(con.getRs().getString("sexo").equalsIgnoreCase("M"))
            {
                jRm.setSelected(true);
            }else
            {
                jRf.setSelected(true);
            }

           jTcidade.setText(con.getRs().getString("cidade_codCidade"));


         
           con.executeStatement("select nome_cidade from cidade where codCidade = "+jTcidade.getText());
           con.getRs().first();

           jCcidade.setSelectedItem(con.getRs().getString("nome_cidade"));
          
           con.executeStatement("select * from cliente order by "+ordem);
           con.getRs().first();
        }catch(Exception e)
        {

        }

    }

    public void atualizaClientes()
    {
        try
        {
            indiceComboUltimo=0;
            jCcliente.removeAllItems();
            con.conecta();
            con.executeStatement("select * from cliente order by "+ordem);
            while(con.getRs().next())
            {
                jCcliente.addItem(con.getRs().getString("nome_cliente"));
                indiceComboUltimo++;
            }
            
            indiceCombo = jCcliente.getSelectedIndex();
        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
        
    }

     public void atualizaCidades()
    {
        try
        {
            con.conecta();
            jCcidade.removeAllItems();
            con.executeStatement("select nome_cidade from view_nome_cidade");
            while(con.getRs().next())
            {
                
                jCcidade.addItem(con.getRs().getString("nome_cidade"));
            }

        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }

    }

     public void limpaCampos()
    {
       jTcodigo.setText("");
       jTnome.setText("");
       jTendereco.setText("");
       jTcpf.setText("");
       jTtel.setText("");
       jTcidade.setText("");
     }
    public static String formatarString(String texto, String mascara) throws ParseException {  
        MaskFormatter mf = new MaskFormatter(mascara);  
        mf.setValueContainsLiteralCharacters(false);  
        return mf.valueToString(texto);  
    }
    
    private void preenchejTable(String filtro)
    {
         DefaultTableModel modelo2 = (DefaultTableModel) jTable1.getModel();
         modelo2.setRowCount(0);
         
         try
         {
              con.executeStatement("select * from cliente c "
                      + " inner join cidade cid on (c.cidade_CodCidade = cid.codCidade)"
                      + " where nome_cliente like '%"+filtro+"%'order by "+ordem);
              while(con.getRs().next())
              {
                   jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer()
                  {  
                        public Component getTableCellRendererComponent(JTable table, Object value,  
                        boolean isSelected, boolean hasFocus, int row, int column)
                        {  
                            super.getTableCellRendererComponent(table, value, isSelected,  
                                hasFocus, row, column); 
                           
                            if (row%2==0) {  
                                setBackground(Color.LIGHT_GRAY); 
                                
                            }else if (row%2 == 1) {  
                                setBackground(null); 
                            }
                             
                             return this;  
                        }  
                    });  
                  
                  
                  modelo2.addRow(new Object[]{con.getRs().getString("codCliente"),con.getRs().getString("nome_cliente")
                  ,con.getRs().getString("telefone"),con.getRs().getString("cpf"),con.getRs().getString("nome_cidade")
                  ,con.getRs().getString("endereco")});
              }
             
         }catch(Exception e)
         {
             
         }
        
    }
     

}
