/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFVendas.java
 *
 * Created on 8/Out/2011, 22:51:51
 */

package br.classesprincipais;

import br.utilitario.Conexao;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import br.utilitario.Data;
import java.awt.Color;
import java.awt.Component;
import java.sql.CallableStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M4RCO5
 */
public final class JFCompras extends javax.swing.JFrame {

    //posiçao do arraylist de codigo do livro
   // private int posCodigo;
    private int posQuant;
    
    private List<Integer> posCodigo = new ArrayList<Integer>();
    
    private int verifica_rows=0;
    private int cont=0;
    private int cont_total=0;
    private Conexao con = new Conexao();
    private String filtro="titulo";
    private String ordem="titulo";
    private Date data = new Date();
    private double valor_total_venda;
    private List<Integer> lista = new ArrayList<Integer>();
    private List<Integer> quantidade = new ArrayList<Integer>();
    private List<Double> valor_unitario = new ArrayList<Double>();
    private List<Double> sub_total = new ArrayList<Double>();
    private double total_venda ;
    public JFCompras() {
        initComponents();
        setLocationRelativeTo(null);
        atualizaTodos();
        atualizaFornecedores();
        jTdata.setText(data.getDate()+"/"+(data.getMonth()+1)+"/"+(data.getYear()+1900));
        jTdata.setEditable(false);
        jTprecoTotal.setText("0.0");
        jTjuros.setText("0.0");
        jTNumParcelas.setText("0");
        jTValorParcela.setText("0.0");
        jTValorRecebido.setText("0.0");
        jPanelParcelado.setVisible(false);
        //jTableDetalhes.setEnabled(false);
       // execProcedure();

        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroupFP = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jCFornecedor = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTdata = new javax.swing.JTextField();
        jLcodForn = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTprecoTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDetalhes = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTValorRecebido = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jRaVista = new javax.swing.JRadioButton();
        jRParcelado = new javax.swing.JRadioButton();
        jPanelParcelado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTNumParcelas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTjuros = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTValorParcela = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTprime_vencimento = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTpesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCresultado = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jRtitulo = new javax.swing.JRadioButton();
        jRautor = new javax.swing.JRadioButton();
        jReditora = new javax.swing.JRadioButton();
        jRano = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jCtodos = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setTitle("Venda de Livros");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens"));

        jLabel13.setText("Fornecedor:");

        jCFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFornecedorActionPerformed(evt);
            }
        });

        jLabel14.setText("Livro(s) : (Selecione um livro para exclui-lo da lista)");

        jLabel15.setText("Valor total :");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/icone_cadastro.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel16.setText("Data da venda :");

        jLcodForn.setText("jLabel17");

        jLabel17.setText("Código fornecedor: ");

        jTableDetalhes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Titulo", "Quantidade", "Valor Unitário", "Sub Total"
            }
        ));
        jTableDetalhes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDetalhesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDetalhes);

        jLabel6.setText("Valor recebido:");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Formas de Pagamento"));

        buttonGroupFP.add(jRaVista);
        jRaVista.setSelected(true);
        jRaVista.setText("Á Vista");
        jRaVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRaVistaActionPerformed(evt);
            }
        });

        buttonGroupFP.add(jRParcelado);
        jRParcelado.setText("Parcelado");
        jRParcelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRParceladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jRaVista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRParcelado)
                .addGap(24, 24, 24))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRaVista)
                    .addComponent(jRParcelado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelParcelado.setBorder(javax.swing.BorderFactory.createTitledBorder("Parcelamento"));

        jLabel3.setText("Número de parcelas:");

        jTNumParcelas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTNumParcelasFocusLost(evt);
            }
        });

        jLabel4.setText("Juros:");

        jLabel5.setText("Valor de cada parcela:");

        jTValorParcela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTValorParcelaFocusGained(evt);
            }
        });

        jLabel7.setText("Primeiro vencimento:");

        javax.swing.GroupLayout jPanelParceladoLayout = new javax.swing.GroupLayout(jPanelParcelado);
        jPanelParcelado.setLayout(jPanelParceladoLayout);
        jPanelParceladoLayout.setHorizontalGroup(
            jPanelParceladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelParceladoLayout.createSequentialGroup()
                .addGroup(jPanelParceladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelParceladoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelParceladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelParceladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNumParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTprime_vencimento, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTValorParcela, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelParceladoLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTjuros, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelParceladoLayout.setVerticalGroup(
            jPanelParceladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParceladoLayout.createSequentialGroup()
                .addGroup(jPanelParceladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNumParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelParceladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelParceladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTjuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelParceladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTprime_vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLcodForn))
                                    .addComponent(jCFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jTdata, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                    .addComponent(jTValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTprecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelParcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(834, 834, 834))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 1475, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLcodForn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15)
                            .addComponent(jTprecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addComponent(jPanelParcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/Salvar.png"))); // NOI18N
        jButton7.setText("Efetuar compra");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/delete.gif"))); // NOI18N
        jButton8.setText("Cancelar compra");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/1_copy_32.png"))); // NOI18N
        jButton9.setText("Nova compra");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/porta.gif"))); // NOI18N
        jButton11.setText("         Sair");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Histórico de compras");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton7, jButton8, jButton9});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtragem de Livros"));

        jLabel1.setText("Preencha com a informação");

        jLabel2.setText("Lista de livros relacionados a busca");

        jCresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCresultadoActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/icone_detalhes.gif"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/meu-orcamento.gif"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton10.setText("Pesquisa completa");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro"));

        jRtitulo.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(jRtitulo);
        jRtitulo.setSelected(true);
        jRtitulo.setText("Titulo");
        jRtitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRtituloActionPerformed(evt);
            }
        });

        jRautor.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(jRautor);
        jRautor.setText("Autor");
        jRautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRautorActionPerformed(evt);
            }
        });

        jReditora.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(jReditora);
        jReditora.setText("Editora");
        jReditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReditoraActionPerformed(evt);
            }
        });

        jRano.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(jRano);
        jRano.setText("Ano de lançamento");
        jRano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRanoActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Categoria");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRtitulo)
                    .addComponent(jRautor)
                    .addComponent(jReditora)
                    .addComponent(jRano)
                    .addComponent(jRadioButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRautor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jReditora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRano))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Todos livros"));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenação"));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Ordem alfabética");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Ano de Lançamento");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton1)
                .addComponent(jRadioButton2))
        );

        jLabel12.setText("Todos livros cadastrados");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/icone_detalhes.gif"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/meu-orcamento.gif"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jCtodos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton3, jButton6});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCtodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton3, jButton6});

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jCresultado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTpesquisa, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(4, 4, 4)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton5});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton2)
                            .addComponent(jButton10)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButton5});

        jMenu1.setText("Sistema");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, 0, 716, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRautorActionPerformed
       filtro = "autor";
    }//GEN-LAST:event_jRautorActionPerformed

    private void jReditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReditoraActionPerformed
        filtro = "editora";
    }//GEN-LAST:event_jReditoraActionPerformed

    private void jRanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRanoActionPerformed
      filtro = "data_lanc";
    }//GEN-LAST:event_jRanoActionPerformed

    private void jRtituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRtituloActionPerformed
        filtro = "titulo";
    }//GEN-LAST:event_jRtituloActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       JFDetalhes aux =  new JFDetalhes(jCresultado);
       aux.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFDetalhes aux =  new JFDetalhes(jCtodos);
        aux.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
       ordem="titulo";
       atualizaTodos();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       ordem="data_lanc";
       atualizaTodos();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFFornecedor aux;
        
        aux = new JFFornecedor();
        aux.setVisible(true);
        
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      adicionaNaLista(jCresultado);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      adicionaNaLista(jCtodos);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
  String codCompra="";

   try
   {
       Data d = new Data();
       String data = d.convertedata(jTdata.getText());

       con.conecta();
       con.executaSql("insert into compra (fornecedor_CodFornecedor,data_compra,valor_total) values (?,?,?)");
       con.getPs().setString(1,jLcodForn.getText());
       con.getPs().setString(2,data);
       con.getPs().setString(3,String.valueOf(total_venda));
       con.getPs().execute();


       con.executaSql("select max(codCompra) from compra");
       while(con.getRs().next())
       {
             codCompra = con.getRs().getString("max(codCompra)");

       }
       
       
       try
       {
            int nume= 0;
            for(int i =0;i<lista.size();i++)
            {
                con.conecta();

                    con.executaSql("insert into itens_compra (livro_CodLivro,preco_total,compra_CodCompra,quantidade,valor_unitario,sub_total) values (?,?,?,?,?,?)");
                    con.getPs().setString(1,String.valueOf(lista.get(i)));
                    con.getPs().setString(2,jTprecoTotal.getText());
                    con.getPs().setString(3,codCompra);
                    con.getPs().setString(4,String.valueOf(quantidade.get(i)));
                    con.getPs().setString(5,String.valueOf(valor_unitario.get(i)));
                    con.getPs().setString(6,String.valueOf(sub_total.get(i)));

                    con.getPs().execute();

                    /*
                     Nesta parte a trigger é acionada para atualizar
                     * o estoque do livro
                     */

            }
         }catch(Exception e)
         {
                javax.swing.JOptionPane.showMessageDialog(null,"itens: "+e);
         }
        
         if(jRParcelado.isSelected()) {
            con.conecta();
            con.executaSql("insert into contas_pagar (compra_codCompra,situacao) values (?,?)");
            con.getPs().setString(1,codCompra);
            con.getPs().setString(2,"aberto");
            con.getPs().execute();

            con.executaSql("select max(codContas_pagar) as codigo from contas_pagar");
            con.getRs().next();
            String codcr = con.getRs().getString("codigo");
            con.getRs().first();

            int qtd = Integer.parseInt(jTNumParcelas.getText());
            while(qtd>0) {

                //Stored Pocedure que insere na tabela parcelas

                CallableStatement callparcela = con.getCon().prepareCall("call pr_insere_parcelas_pagar(?,?,?,?,?)");
                callparcela.setString(1,codcr);
                callparcela.setString(2,jTValorParcela.getText());
                callparcela.setString(3,jTValorRecebido.getText());
                callparcela.setString(4,jTNumParcelas.getText());
                callparcela.setString(5,"N");
                callparcela.execute();

                qtd--;
            }

        }

       javax.swing.JOptionPane.showMessageDialog(null,"Compra efetuada com sucesso");
       zerarVariaveis();


   }catch(Exception e)
   {
       javax.swing.JOptionPane.showMessageDialog(null,e);
       
   }
      
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jCFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFornecedorActionPerformed
       try
        {
            con.conecta();
            boolean achei=false;
            con.executeStatement("select nome_fornecedor,codFornecedor from fornecedor");
            con.getRs().first();
            while(achei==false)
            {
                if(con.getRs().getString("nome_fornecedor").equalsIgnoreCase((String)jCFornecedor.getSelectedItem()))
                {
                    achei=true;
                }else
                {
                    con.getRs().next();
                }
                
            }

            jLcodForn.setText(con.getRs().getString("codFornecedor"));

        }catch(Exception e)
        {
             //javax.swing.JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jCFornecedorActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        zerarVariaveis();
        javax.swing.JOptionPane.showMessageDialog(null,"Venda cancelada");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        zerarVariaveis();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jCresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCresultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCresultadoActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       JFPesquisa aux = new JFPesquisa();
       aux.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jRParceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRParceladoActionPerformed
        jTNumParcelas.setText("2");
        jPanelParcelado.setVisible(true);
        jTNumParcelas.grabFocus();
    }//GEN-LAST:event_jRParceladoActionPerformed

    private void jRaVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRaVistaActionPerformed
        jPanelParcelado.setVisible(false);
    }//GEN-LAST:event_jRaVistaActionPerformed

    private void jTValorParcelaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTValorParcelaFocusGained
        atualizaValorParcelas();
    }//GEN-LAST:event_jTValorParcelaFocusGained

    private void jTNumParcelasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTNumParcelasFocusLost
        atualizaValorParcelas();
    }//GEN-LAST:event_jTNumParcelasFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        atualizaFornecedores();      
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         con.fechaConexao();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
       {
           jCresultado.removeAllItems();
           String pesquisa ="";
           pesquisa = jTpesquisa.getText();
           con.conecta();

           con.executaSql("select * from livro where "+filtro+" like '%"+pesquisa+"%' ");
           while(con.getRs().next())
           {
               if(con.getRs().getString("titulo").equalsIgnoreCase(""))
               {

               }else
               {
                   jCresultado.addItem(con.getRs().getString("titulo"));

               }
               
           }

           if(jCresultado.getItemCount()<=0)
           {
               jCresultado.addItem("Nao foi encontrado nenhum livro");
           }

       }catch(Exception e)
       {
           javax.swing.JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTableDetalhesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDetalhesMouseClicked
       
        try
        {
            int i = JOptionPane.showConfirmDialog(null,"Deseja remover este livro da lista ?");
            if(i==0)
            {
                double valor=0;
                DefaultTableModel modelo = (DefaultTableModel) jTableDetalhes.getModel();

                String x = String.valueOf(jTableDetalhes.getValueAt(jTableDetalhes.getSelectedRow(), 0));
                int codigo = Integer.parseInt(x);
                valor = Double.parseDouble(String.valueOf(jTableDetalhes.getValueAt(jTableDetalhes.getSelectedRow(), 4))); 

               //remove o código do livro que foi selecionado na grid
               lista.remove( lista.indexOf(codigo) );  
               total_venda-=valor;
               jTprecoTotal.setText(String.valueOf(total_venda));

               //remove a linha selecionada
               ((DefaultTableModel) jTableDetalhes.getModel()).removeRow(jTableDetalhes.getSelectedRow()); 

               //decrementa o contador da quantidade e do codigo do livro
               cont--;
                
            }

            
          

        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        
       
    }//GEN-LAST:event_jTableDetalhesMouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       JFComprasFeitas aux = new JFComprasFeitas();
       aux.setVisible(true);
       aux = null;
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroupFP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jCFornecedor;
    private javax.swing.JComboBox jCresultado;
    private javax.swing.JComboBox jCtodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLcodForn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelParcelado;
    private javax.swing.JRadioButton jRParcelado;
    private javax.swing.JRadioButton jRaVista;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRano;
    private javax.swing.JRadioButton jRautor;
    private javax.swing.JRadioButton jReditora;
    private javax.swing.JRadioButton jRtitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTNumParcelas;
    private javax.swing.JTextField jTValorParcela;
    private javax.swing.JTextField jTValorRecebido;
    private javax.swing.JTable jTableDetalhes;
    private javax.swing.JTextField jTdata;
    private javax.swing.JTextField jTjuros;
    private javax.swing.JTextField jTpesquisa;
    private javax.swing.JTextField jTprecoTotal;
    private javax.swing.JTextField jTprime_vencimento;
    // End of variables declaration//GEN-END:variables


    public void atualizaValorParcelas()
    {
        double vTotal=0,vCadaParcela=0;
        int numParcelas=0;
        
        numParcelas = Integer.parseInt(jTNumParcelas.getText());
        vTotal = Double.parseDouble(jTprecoTotal.getText());
        vCadaParcela = (vTotal / numParcelas);
        jTValorParcela.setText(String.valueOf(Math.ceil(vCadaParcela)));
    }
    
    public void adicionaNaLista(JComboBox combo)
    {   //Variaveis que serão usadas neste método
        
        //Armazena titulo do livro selecionado
        String titulo = (String)combo.getSelectedItem();
        
        //variavel para recuperar preço dos livros
        double preco = 0,subtotal=0;
        
        //variavel para recuperar o estoque atual do livro
        int estoque_atual=0;
        preco = Double.parseDouble(jTprecoTotal.getText());
        
        //variavel para quantidade de livro informado
        int quant=0;
        int pos=0;
        
        //variavel armazena o total da venda
        double total2=0;
        total2 = Double.parseDouble(jTprecoTotal.getText());
        
        
        try
        {
            //Adiciona a quantidade de cada livro e armazena no arraylist
            quant = Integer.parseInt(JOptionPane.showInputDialog("Informe a quantidade:",1));
            quantidade.add(quant);
            pos=quantidade.size();
            System.out.println("size do qtd"+pos);
            System.out.println("cont = "+cont);
            
        }catch(Exception e)
        {
             //javax.swing.JOptionPane.showMessageDialog(null,"erro 1"+ e);
        }
        
        try
        {

            con.executaSql("select titulo,codLivro,preco_venda from livro where titulo =  '"+titulo+"'");
            con.getRs().next();

            double preco_venda =Double.parseDouble(con.getRs().getString("preco_venda"));
            double sub = preco_venda * quantidade.get(cont);
            double soma=0;
            sub_total.add(sub);
            valor_unitario.add(preco_venda);
            lista.add(Integer.parseInt(con.getRs().getString("codLivro")));
            posCodigo.add(lista.get(cont)); //lista.size();

           //  System.out.println("posicao  "+posCodigo.get(cont));

            soma=total2+sub;
            jTprecoTotal.setText(String.valueOf(soma));
            total_venda= soma;
           // jTlivros.setText(jTlivros.getText()+(String)combo.getSelectedItem()+" \t "+quant+"\n");
            cont++;

            //jtableDetalhes
            try
            {   
                con.conecta();

                DefaultTableModel modelo = (DefaultTableModel) jTableDetalhes.getModel();
                con.executeStatement("select * from livro where livro.codLivro = "+lista.get(lista.size()-1));

                if(verifica_rows==0)
                {
                   modelo.setRowCount(0); 
                   verifica_rows=1;
                }


                while(con.getRs().next())
                {
                     jTableDetalhes.setDefaultRenderer(Object.class, new DefaultTableCellRenderer()
                        {  
                            public Component getTableCellRendererComponent(JTable table, Object value,  
                            boolean isSelected, boolean hasFocus, int row, int column)
                            {  
                                super.getTableCellRendererComponent(table, value, isSelected,  
                                    hasFocus, row, column); 

                                if (row%2==0) {  
                                    setBackground(Color.LIGHT_GRAY); 

                                }else if (row%2 == 1) {  
                                    setBackground(null); 
                                }

                                 return this;  
                            }  
                      }); 
                    
                    subtotal = Double.parseDouble(con.getRs().getString("preco_venda"));
                    modelo.addRow(new Object[]{con.getRs().getString("codLivro"), con.getRs().getString("titulo"),
                            quant,con.getRs().getString("preco_venda"),(quant * subtotal)
                    });


                }
                con.getRs().first();


            }catch(SQLException e)
            {
               javax.swing.JOptionPane.showMessageDialog(null,"adicionando na tabela: "+ e);
            }


        }catch(Exception e)
        {
             javax.swing.JOptionPane.showMessageDialog(null,"erro 2"+ e);
        }
        

        
    }
    //Adiciona livros cadastrados no combobox
    public void atualizaTodos()
    {
       try
       {
           jCtodos.removeAllItems();
           con.conecta();
           con.executeStatement("select * from livro order by "+ordem);
           while(con.getRs().next())
           {
               jCtodos.addItem(con.getRs().getString("titulo"));
           }
         
           con.getRs().first();

           

       }catch(Exception e)
       {
           javax.swing.JOptionPane.showMessageDialog(null, e);
       }
        
    }
    
    //Zerar variaveis
    public void zerarVariaveis()
    {
        try
        {
            quantidade.clear();  
            lista.clear();
          //  jTlivros.setText("");
            jTprecoTotal.setText("0.0");
            jTjuros.setText("0.0");
            jTNumParcelas.setText("0");
            jTValorParcela.setText("0.0");
            jTValorRecebido.setText("0.0");
            con.getCon().close();
            valor_unitario.clear();
            sub_total.clear();
            cont=0;
            total_venda=0;
            verifica_rows=0;
            DefaultTableModel modelo = (DefaultTableModel) jTableDetalhes.getModel();
            modelo.setRowCount(0);
            jPanelParcelado.setVisible(false);
            jRaVista.setSelected(true);
            
            
        }catch(Exception e)
        {
            System.out.println(e);
        }
   
    }


    
public void preenchejTable()
    {
        try
        {
            con.conecta();
            
            DefaultTableModel modelo = (DefaultTableModel) jTableDetalhes.getModel();
            con.executeStatement("select sum(sub_total) as valor_total_geral, sum(quantidade) as quantidade_total,codVenda,data_venda,nome_cliente,preco_total from venda "+
                    " inner join itens_venda on venda.codVenda = itens_venda.venda_CodVenda" +
                    " inner join livro on livro.codLivro = itens_venda.livro_codLivro"+
                    " inner join cliente on venda.cliente_CodCliente = cliente.codCliente"+
                    " group by venda.codVenda order by "+ordem+" desc ");

            modelo.setRowCount(0);
            
            while(con.getRs().next())
            {
                modelo.addRow(new Object[]{con.getRs().getString("codVenda"), con.getRs().getString("nome_cliente"),
                        con.getRs().getString("quantidade_total"),con.getRs().getString("data_venda"),con.getRs().getString("valor_total_geral")
                });


            }
             con.getRs().first();

         

        }catch(Exception e)
        {
           javax.swing.JOptionPane.showMessageDialog(null, e);
        }
        
    }
//atualiza qtde de livros comprado pelo cliente
public void execProcedureQtdeComprado()
{
    try
    {
        con.conecta();
        //CallableStatement call = con.getCon().prepareCall("call cadautor(1)");
        CallableStatement call = con.getCon().prepareCall("call qtde_comprado_cliente ()");
        call.execute();
        //String x = call.getString(1);
        
    /*CallableStatement call = con.getCon().prepareCall("EXEC listar_cidade(?)");  
    call.setInt(1, 1);  
    call.registerOutParameter(1,java.sql.Types.INTEGER);  
    call.
         System.out.println("proceeeeee  "+x)

    call.execute();  

    String x = call.getString(1); 
        System.out.println("proceeeeee  "+x);*/
    }catch(SQLException e)
    {
        JOptionPane.showMessageDialog(null,e);
    }
   
}
public void atualizaFornecedores()
    {
       try
       {
           jCFornecedor.removeAllItems();
           con.conecta();
           con.executaSql("select * from fornecedor");
           while(con.getRs().next())
           {
               jCFornecedor.addItem(con.getRs().getString("nome_fornecedor"));
           }


       }catch(Exception e)
       {
           //javax.swing.JOptionPane.showMessageDialog(null, e);
       }

    }


}
