/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.classesprincipais;

import br.utilitario.Conexao;
import br.utilitario.Data;
import br.utilitario.ToolNumericKeyAdapter;
import java.awt.Color;
import java.awt.Component;
import java.awt.HeadlessException;
import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author linux
 */
public class JFEntrada extends javax.swing.JFrame {

    
        private int posQuant;
    
    private List<Integer> posCodigo = new ArrayList<Integer>();
    
    private int verifica_rows=0;
    private int cont=0;
    private int cont_total=0;
    private Conexao con = new Conexao();
    private String filtro="titulo";
    private String ordem="titulo";
    private Date data = new Date();
    private double valor_total_venda;
    private List<Integer> lista = new ArrayList<Integer>();
    private List<Integer> quantidade = new ArrayList<Integer>();
    private List<Double> valor_unitario = new ArrayList<Double>();
    private List<Double> sub_total = new ArrayList<Double>();
    private double total_venda ;
    private String precounit="";
    /**
     * Creates new form JFEntrada
     */
    public JFEntrada() {
        initComponents();
        
        setLocationRelativeTo(null);
        atualizaTodos();
       
        atualizaFornecedores();
        TableColumnModel columnModel = jTableDetalhes.getColumnModel();
        columnModel.getColumn(0).setWidth(10);
       /* jTdata.setText(data.getDate()+"/"+(data.getMonth()+1)+"/"+(data.getYear()+1900));
        jTdata.setEditable(false);
        jTprecoTotal.setText("0.0");
       /* jTjuros.setText("0.0");
        jTNumParcelas.setText("0");
        jTValorParcela.setText("0.0");
        jTValorRecebido.setText("0.0");
        jPanelParcelado.setVisible(false);*/
        //jTableDetalhes.setEnabled(false);
       // execProcedure();
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTproduto = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jCFornecedor = new javax.swing.JComboBox();
        jCtodos = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTprecoTotal = new JNumberField.JNumberField();
        jTqtd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTobs = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jTnf = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDetalhes = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLcodForn = new javax.swing.JLabel();
        jTdesc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTprecounic = new JNumberField.JNumberField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Pesquisar Fornecedor");

        jButton1.setText("Fornecedores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Pesquisa de Produto");

        jTproduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTprodutoKeyReleased(evt);
            }
        });

        jButton3.setText("Produtos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Data");

        jCFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFornecedorActionPerformed(evt);
            }
        });

        jCtodos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCtodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCtodosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCtodosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCtodosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCtodosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCtodosMouseReleased(evt);
            }
        });
        jCtodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtodosActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantidade");

        jLabel6.setText("Total");

        jTqtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTqtdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTqtdKeyReleased(evt);
            }
        });

        jLabel7.setText("Observaçoes");

        jTobs.setColumns(20);
        jTobs.setRows(5);
        jScrollPane1.setViewportView(jTobs);

        jButton5.setText("Atualizar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setText("Nota Fiscal");

        jTnf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTnfKeyPressed(evt);
            }
        });

        jTableDetalhes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableDetalhes);

        jButton4.setText("Salvar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Excluir");

        jButton7.setText("Novo");

        jButton8.setText("jButton8");

        jLabel17.setText("Código fornecedor: ");

        jLcodForn.setText("jLabel17");

        jLabel10.setText("Descricao do Produto");

        jLabel11.setText("Preço Unitário");

        jTprecounic.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTdesc)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(126, 126, 126))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField2)
                                        .addGap(6, 6, 6)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLcodForn))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(399, 399, 399)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jCFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton5))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCtodos, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jTnf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTqtd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jTprecounic, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(99, 99, 99))
                                            .addComponent(jTprecoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLcodForn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jCFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCtodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTprecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTqtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTprecounic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFornecedorActionPerformed
       try
        {
            con.conecta();
            boolean achei=false;
            con.executeStatement("select nome_fornecedor,codFornecedor from fornecedor");
            con.getRs().first();
            while(achei==false)
            {
                if(con.getRs().getString("nome_fornecedor").equalsIgnoreCase((String)jCFornecedor.getSelectedItem()))
                {
                    achei=true;
                }else
                {
                    con.getRs().next();
                }
                
            }
              
            jLcodForn.setText(con.getRs().getString("codFornecedor"));
           

        }catch(Exception e)
        {
             //javax.swing.JOptionPane.showMessageDialog(null,e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jCFornecedorActionPerformed

    private void jCtodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtodosActionPerformed
  try
       {
           
           con.conecta();
           con.executeStatement("select * from livro where titulo='"+jCtodos.getSelectedItem()+"'");
           con.getRs().next();
           jTprecounic.setText(con.getRs().getString("preco_custo"));
           
           con.conecta();
           con.executeStatement("select titulo from livro ");
          // System.out.println(precounit);
       }catch(Exception e){}   
    }//GEN-LAST:event_jCtodosActionPerformed

    private void jTprodutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTprodutoKeyReleased
    
    }//GEN-LAST:event_jTprodutoKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          JFLivros1 aux = new JFLivros1();
          aux.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JFFornecedor outra = new JFFornecedor();
       outra.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          Data d = new Data();
       // String data = d.convertedata(jTano.getText());
        try
       {
           /*if(jTtitulo.getText().equalsIgnoreCase(""))
           {
               JOptionPane.showMessageDialog(null,"É obrigatório preencher o campo Titulo");
           }else 
           {
                   //Data d = new Data();
               //String data = d.convertedata(jTano.getText());
               if(!jTcodigo.getText().equalsIgnoreCase(""))
               {
                   java.util.Date pega = jDateChooserLanc.getDate();
                        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
                        String data3  = formato.format(pega);
                        System.out.print(data3);
                        
                  con.conecta();
                  con.executaSql("update livro set titulo = ?,editora_CodEditora = ?,data_lanc = ?,preco_custo = ? ,preco_venda = ?,"
                           + "categoria_CodCategoria = ?,estoque_atual = ?,estoque_minimo = ?,resenha = ?,autor_CodAutor = ?,isbn=?, foto =? where codLivro =  "+jTcodigo.getText());

                   con.getPs().setString(1,jTtitulo.getText());
                   con.getPs().setString(2,codEditora);
                   con.getPs().setString(3,data3);
                   con.getPs().setFloat(4,jTprecoCusto.getValue().floatValue());
                   con.getPs().setFloat(5,jTprecoVenda.getValue().floatValue());
                   con.getPs().setString(6,codCategoria);
                   con.getPs().setString(7,jTestoqueatual.getText());
                   con.getPs().setString(8,jTestoqueminimo.getText());
                   con.getPs().setString(9,jTresenha.getText());
                   con.getPs().setString(10,codAutor);
                   con.getPs().setString(11,jTIsbn.getText());
                   con.getPs().setString(12,jTfoto.getText());

                   con.getPs().execute();

                   javax.swing.JOptionPane.showMessageDialog(null,"Alterado com sucesso !");
                   atualiza();
                   preenchejTable("");


               }else*/
               {
                   
                       java.util.Date pega = jDateChooser1.getDate();
                        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
                        String data3  = formato.format(pega);
                        System.out.print(data3);
                        
                   //Pega código produto
                   String codLivro="";
                   con.conecta();
                   con.executeStatement("select codLivro from livro where titulo='"+jCtodos.getSelectedItem()+"'");
                   con.getRs().first();
                   codLivro=con.getRs().getString("codLivro");
                   
                   con.conecta();
                   con.executaSql("insert into entrada (codProduto,codFornecedor,data,qtd,obs,total,precoUnic) values (?,?,?,?,?,?,?)");

                   con.getPs().setString(1,codLivro);
                   con.getPs().setString(2,jLcodForn.getText());
                   con.getPs().setString(3,data3);
                   con.getPs().setString(4,jTqtd.getText());
                   con.getPs().setString(5,jTobs.getText());
                   con.getPs().setFloat(6,jTprecoTotal.getValue().floatValue());
                   con.getPs().setFloat(7,jTprecounic.getValue().floatValue());
 
                   con.getPs().execute();
                   
                   javax.swing.JOptionPane.showMessageDialog(null,"Salvo com sucesso");
                 /*  atualiza();
                   javax.swing.JOptionPane.showMessageDialog(null,"Salvo com sucesso");
                   limpaCampos();
                   preenchejTable("");*/

               }//fim  2 a  a   else

       
           
       }catch(Exception e)
       {
           javax.swing.JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCtodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCtodosMouseClicked
    
        
    }//GEN-LAST:event_jCtodosMouseClicked

    private void jCtodosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCtodosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jCtodosMouseEntered

    private void jCtodosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCtodosMouseExited
        
    }//GEN-LAST:event_jCtodosMouseExited

    private void jCtodosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCtodosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCtodosMousePressed

    private void jCtodosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCtodosMouseReleased
      
    }//GEN-LAST:event_jCtodosMouseReleased

    private void jTqtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTqtdKeyReleased
      try
      {
 
          double v1 ;
          double v2,total;

          v1 = Double.parseDouble(jTqtd.getText());
          v2 =  jTprecounic.getValue().doubleValue();
          total=v1*v2;
          jTprecoTotal.setValue(new BigDecimal(v1*v2));
  
         //  JOptionPane.showMessageDialog(null, lista);
      }catch(Exception e){  }
    }//GEN-LAST:event_jTqtdKeyReleased

    private void jTqtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTqtdKeyPressed
       jTqtd.addKeyListener(new ToolNumericKeyAdapter(10, false));
    }//GEN-LAST:event_jTqtdKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        atualizaTodos();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       atualizaFornecedores();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTnfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnfKeyPressed
       jTnf.addKeyListener(new ToolNumericKeyAdapter(30, false));
    }//GEN-LAST:event_jTnfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jCFornecedor;
    private javax.swing.JComboBox jCtodos;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLcodForn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDetalhes;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTdesc;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTnf;
    private javax.swing.JTextArea jTobs;
    private JNumberField.JNumberField jTprecoTotal;
    private JNumberField.JNumberField jTprecounic;
    private javax.swing.JTextField jTproduto;
    private javax.swing.JTextField jTqtd;
    // End of variables declaration//GEN-END:variables

    /*    public void atualizaValorParcelas()
    {
        double vTotal=0,vCadaParcela=0;
        int numParcelas=0;
        
        numParcelas = Integer.parseInt(jTNumParcelas.getText());
        vTotal = Double.parseDouble(jTprecoTotal.getText());
        vCadaParcela = (vTotal / numParcelas);
        jTValorParcela.setText(String.valueOf(Math.ceil(vCadaParcela)));
    }*/
    
    public void adicionaNaLista(JComboBox combo)
    {   //Variaveis que serão usadas neste método
        
        //Armazena titulo do livro selecionado
        String titulo = (String)combo.getSelectedItem();
        
        //variavel para recuperar preço dos livros
        double preco = 0,subtotal=0;
        
        //variavel para recuperar o estoque atual do livro
        int estoque_atual=0;
        preco = Double.parseDouble(jTprecoTotal.getText());
        
        //variavel para quantidade de livro informado
        int quant=0;
        int pos=0;
        
        //variavel armazena o total da venda
        double total2=0;
        total2 = Double.parseDouble(jTprecoTotal.getText());
        
        
        try
        {
            //Adiciona a quantidade de cada livro e armazena no arraylist
            quant = Integer.parseInt(JOptionPane.showInputDialog("Informe a quantidade:",1));
            quantidade.add(quant);
            pos=quantidade.size();
            System.out.println("size do qtd"+pos);
            System.out.println("cont = "+cont);
            
        }catch(Exception e)
        {
             //javax.swing.JOptionPane.showMessageDialog(null,"erro 1"+ e);
        }
        
        try
        {

            con.executaSql("select titulo,codLivro,preco_venda from livro where titulo =  '"+titulo+"'");
            con.getRs().next();

            double preco_venda =Double.parseDouble(con.getRs().getString("preco_venda"));
            double sub = preco_venda * quantidade.get(cont);
            double soma=0;
            sub_total.add(sub);
            valor_unitario.add(preco_venda);
            lista.add(Integer.parseInt(con.getRs().getString("codLivro")));
            posCodigo.add(lista.get(cont)); //lista.size();

           //  System.out.println("posicao  "+posCodigo.get(cont));

            soma=total2+sub;
            jTprecoTotal.setText(String.valueOf(soma));
            total_venda= soma;
           // jTlivros.setText(jTlivros.getText()+(String)combo.getSelectedItem()+" \t "+quant+"\n");
            cont++;

            //jtableDetalhes
            try
            {   
                con.conecta();

                DefaultTableModel modelo = (DefaultTableModel) jTableDetalhes.getModel();
                con.executeStatement("select * from livro where livro.codLivro = "+lista.get(lista.size()-1));

                if(verifica_rows==0)
                {
                   modelo.setRowCount(0); 
                   verifica_rows=1;
                }


                while(con.getRs().next())
                {
                     jTableDetalhes.setDefaultRenderer(Object.class, new DefaultTableCellRenderer()
                        {  
                            public Component getTableCellRendererComponent(JTable table, Object value,  
                            boolean isSelected, boolean hasFocus, int row, int column)
                            {  
                                super.getTableCellRendererComponent(table, value, isSelected,  
                                    hasFocus, row, column); 

                                if (row%2==0) {  
                                    setBackground(Color.LIGHT_GRAY); 

                                }else if (row%2 == 1) {  
                                    setBackground(null); 
                                }

                                 return this;  
                            }  
                      }); 
                    
                    subtotal = Double.parseDouble(con.getRs().getString("preco_venda"));
                    modelo.addRow(new Object[]{con.getRs().getString("codLivro"), con.getRs().getString("titulo"),
                            quant,con.getRs().getString("preco_venda"),(quant * subtotal)
                    });


                }
                con.getRs().first();


            }catch(SQLException e)
            {
               javax.swing.JOptionPane.showMessageDialog(null,"adicionando na tabela: "+ e);
            }


        }catch(Exception e)
        {
             javax.swing.JOptionPane.showMessageDialog(null,"erro 2"+ e);
        }
        

        
    }
    //Adiciona livros cadastrados no combobox
    public void atualizaTodos()
    {
       try
       {
           jCtodos.removeAllItems();
           con.conecta();
           con.executeStatement("select * from livro order by "+ordem);
           while(con.getRs().next())
           {
               jCtodos.addItem(con.getRs().getString("titulo"));
           }
         
            con.getRs().first();

           con.getCon().close();

       }catch(Exception e)
       {
           //javax.swing.JOptionPane.showMessageDialog(null, e);
       }
        
    }
    
    //Zerar variaveis
    public void zerarVariaveis()
    {
        try
        {
            quantidade.clear();  
            lista.clear();
          //  jTlivros.setText("");
            jTprecoTotal.setText("0.0");
           /* jTjuros.setText("0.0");
            jTNumParcelas.setText("0");
            jTValorParcela.setText("0.0");
            jTValorRecebido.setText("0.0");*/
            con.getCon().close();
            valor_unitario.clear();
            sub_total.clear();
            cont=0;
            total_venda=0;
            verifica_rows=0;
            DefaultTableModel modelo = (DefaultTableModel) jTableDetalhes.getModel();
            modelo.setRowCount(0);
           /* jPanelParcelado.setVisible(false);
            jRaVista.setSelected(true);*/
            
            
        }catch(Exception e)
        {
            System.out.println(e);
        }
   
    }


    
public void preenchejTable()
    {
        try
        {
            con.conecta();
            
            DefaultTableModel modelo = (DefaultTableModel) jTableDetalhes.getModel();
            con.executeStatement("select sum(sub_total) as valor_total_geral, sum(quantidade) as quantidade_total,codVenda,data_venda,nome_cliente,preco_total from venda "+
                    " inner join itens_venda on venda.codVenda = itens_venda.venda_CodVenda" +
                    " inner join livro on livro.codLivro = itens_venda.livro_codLivro"+
                    " inner join cliente on venda.cliente_CodCliente = cliente.codCliente"+
                    " group by venda.codVenda order by "+ordem+" desc ");

            modelo.setRowCount(0);
            
            while(con.getRs().next())
            {
                modelo.addRow(new Object[]{con.getRs().getString("codVenda"), con.getRs().getString("nome_cliente"),
                        con.getRs().getString("quantidade_total"),con.getRs().getString("data_venda"),con.getRs().getString("valor_total_geral")
                });


            }
             con.getRs().first();

         

        }catch(Exception e)
        {
           javax.swing.JOptionPane.showMessageDialog(null, e);
        }
        
    }
//atualiza qtde de livros comprado pelo cliente
public void execProcedureQtdeComprado()
{
    try
    {
        con.conecta();
        //CallableStatement call = con.getCon().prepareCall("call cadautor(1)");
        CallableStatement call = con.getCon().prepareCall("call qtde_comprado_cliente ()");
        call.execute();
        //String x = call.getString(1);
        
    /*CallableStatement call = con.getCon().prepareCall("EXEC listar_cidade(?)");  
    call.setInt(1, 1);  
    call.registerOutParameter(1,java.sql.Types.INTEGER);  
    call.
         System.out.println("proceeeeee  "+x)

    call.execute();  

    String x = call.getString(1); 
        System.out.println("proceeeeee  "+x);*/
    }catch(SQLException e)
    {
        JOptionPane.showMessageDialog(null,e);
    }
   
}
public void atualizaFornecedores()
    {
       try
       {
           jCFornecedor.removeAllItems();
           con.conecta();
           con.executaSql("select nome_fornecedor from fornecedor");
           while(con.getRs().next())
           {
               jCFornecedor.addItem(con.getRs().getString("nome_fornecedor"));
           }
           con.getRs().first();
 
           
       }catch(Exception e)
       {
           //javax.swing.JOptionPane.showMessageDialog(null, e);
       }

    }

}
