/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFCliente.java
 *
 * Created on 8/Out/2011, 22:38:32
 */

package br.classesprincipais;
import br.utilitario.Conexao;
import br.utilitario.ToolNumericKeyAdapter;

import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author M4RCO5
 */
public class JFFornecedor extends javax.swing.JFrame {

    /** Creates new form JFCliente */
    Conexao con = new Conexao();
    private String ordem="nome_fornecedor";
    private String sexo = "M";
    int inicia=0;
    private int  navegar = 0;//para saber qual botao foi clicado
    private int inicia_combo =0;
    private int indiceCombo =0;
    private int indiceComboUltimo=0;
    public JFFornecedor() {
        initComponents();
        /*try
        {
            jCfornecedor.removeAllItems();
            con.conecta();
            
            con.executeStatement("select * from fornecedor order by "+ordem);
            while(con.getRs().next())
            {
                jCfornecedor.addItem(con.getRs().getString("nome_fornecedor"));
            } 
        }catch(Exception e)
        {
            
        }
         */
        atualizaFornecedor();
       
        preenchejTable("");
        
       
        setLocationRelativeTo(null);
        jTcodigo.setEditable(false);
        
        
        try
        {
           con.conecta();
           con.executeStatement("select * from fornecedor order by "+ordem); 
            
        }catch(Exception e )
        {
                       
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTtel = new javax.swing.JTextField();
        jTendereco = new javax.swing.JTextField();
        jTemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCfornecedor = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTpesquisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTcnpj = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTcidade = new javax.swing.JTextField();
        jCestado = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jTcomplemento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTinscMun = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTInscEst = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTnumero = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTbairro = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de fornecedores");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Fornecedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome/Razão Social");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));
        jPanel1.add(jTnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 350, -1));

        jLabel2.setText("Email.:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel3.setText("Telefone.:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel4.setText("Endereço.:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jTtel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTtelKeyPressed(evt);
            }
        });
        jPanel1.add(jTtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 230, -1));
        jPanel1.add(jTendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 220, -1));
        jPanel1.add(jTemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 290, -1));

        jLabel5.setText("Fornecedores.:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jCfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCfornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jCfornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 580, -1));

        jLabel6.setText("Código.:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jTcodigo.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.add(jTcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cód", "Nome", "Telefone", "Endereço", "Cidade", "CNPJ"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 670, 200));

        jLabel9.setText("Pesquisa.:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, -1, -1));
        jPanel1.add(jTpesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 510, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/ampliar-lupa-icone.gif"))); // NOI18N
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, 24));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 690, 16));

        jLabel7.setText("Cidade. :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        jLabel8.setText("CNPJ/CPF");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 60, -1));
        jPanel1.add(jTcnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 350, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/Save.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 126, -1));

        jButton2.setText("<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 97, 31));

        jButton3.setText("<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 91, 31));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/Split.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 126, -1));

        jButton4.setText(">");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 103, 31));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/delete2.JPG"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 126, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/porta.gif"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 126, 45));

        jButton9.setText(">>");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 97, 31));

        jLabel10.setText("Estado");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));
        jPanel1.add(jTcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 190, -1));

        jCestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));
        jPanel1.add(jCestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 50, -1));

        jLabel11.setText("Complemento");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        jPanel1.add(jTcomplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 300, -1));

        jLabel12.setText("Inscrição Municipal");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jTinscMun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTinscMunKeyPressed(evt);
            }
        });
        jPanel1.add(jTinscMun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 180, -1));

        jLabel13.setText("Inscrição Estadual");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jTInscEst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTInscEstKeyPressed(evt);
            }
        });
        jPanel1.add(jTInscEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 180, -1));

        jLabel14.setText("Numero");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jTnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTnumeroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTnumeroKeyReleased(evt);
            }
        });
        jPanel1.add(jTnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 60, -1));

        jLabel15.setText("Bairro");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));
        jPanel1.add(jTbairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 110, -1));

        jMenu1.setText("Sistema");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCfornecedorActionPerformed

    if(inicia_combo==1){
       try
       {
           //con.conecta();
           
           boolean achei =false;
           //con.executeStatement("select * from fornecedor order by "+ordem);
           con.getRs().first();
           while(achei==false)
           {
               if(con.getRs().getString("nome_fornecedor").equals(jCfornecedor.getSelectedItem()))
               {
                   achei = true;
               }else
               {
                   con.getRs().next();
               }
           }

           mostraDados();
          

       }catch(Exception e)
       {
         //  javax.swing.JOptionPane.showMessageDialog(null, e);
       }

     }

     inicia_combo=1;
    }//GEN-LAST:event_jCfornecedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        con.fechaConexao();
    }//GEN-LAST:event_formWindowClosing

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         try
       {
           if(!jTcodigo.getText().equalsIgnoreCase(""))
           {
               con.conecta();
               con.executaSql("update  fornecedor set nome_fornecedor='"+jTnome.getText()+"',"
                       + "telefone='"+jTtel.getText()+"', email='"+jTemail.getText()+"',cnpj= '"+jTcnpj.getText()+"', endereco='"+jTendereco.getText()+"',"
                       + "cidade='"+jTcidade.getText()+"',inscmun='"+jTinscMun.getText()+"',inscest='"+jTInscEst.getText()+"',"+
                       " estado='"+(String)jCestado.getSelectedItem()+"',complemento='"+jTcomplemento.getText()+"',numero='"+jTnumero.getText()+"',bairro='"+jTbairro.getText()+"'"+ 
                       " where codFornecedor = "+jTcodigo.getText());

               con.getPs().execute();

               atualizaFornecedor() ;
               preenchejTable("");
               javax.swing.JOptionPane.showMessageDialog(null,"Alterado com sucesso");

           }else
           {
               con.conecta();
               con.executaSql("insert into fornecedor(nome_fornecedor,telefone,cnpj,endereco,email,cidade,numero,estado,inscmun,inscest,complemento,bairro) values(?,?,?,?,?,?,?,?,?,?,?,?)");
               con.getPs().setString(1,jTnome.getText());
               con.getPs().setString(2,jTtel.getText());
               con.getPs().setString(3,jTcnpj.getText());
               con.getPs().setString(4,jTendereco.getText());
               con.getPs().setString(5,jTemail.getText());
               con.getPs().setString(6,jTcidade.getText());
               con.getPs().setString(7,jTnumero.getText());
               con.getPs().setString(8,(String)jCestado.getSelectedItem());
               con.getPs().setString(9,jTinscMun.getText());
               con.getPs().setString(10,jTInscEst.getText());
               con.getPs().setString(11,jTcomplemento.getText());
               con.getPs().setString(12,jTbairro.getText());
               con.getPs().execute();

               atualizaFornecedor() ;
               preenchejTable("");
               javax.swing.JOptionPane.showMessageDialog(null,"Salvo com sucesso");

           }
           
       }catch(SQLException e)
       {
           javax.swing.JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      jTcodigo.setText("");
       jTnome.setText("");
       jTendereco.setText("");
       jTemail.setText("");
       jTtel.setText("");
       jTcidade.setText("");
       jTcnpj.setText("");
       jTbairro.setText("");
       jTnumero.setText("");
       jTinscMun.setText("");
       jTInscEst.setText("");
       jCestado.setSelectedItem("MG");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
           try
       {
           con.conecta();

           int i = JOptionPane.showConfirmDialog(null,"Deseja excluir o fornecedor : "+jTnome.getText()+" ? ");
           if(i==0)
           {
              con.executaSql("delete from fornecedor where codFornecedor = "+jTcodigo.getText());
              con.getPs().execute();

              atualizaFornecedor() ;
              preenchejTable("");
              javax.swing.JOptionPane.showMessageDialog(null, "Excluido com sucesso");

           }else
           {
               javax.swing.JOptionPane.showMessageDialog(null, "Exclusao cancelada");
           }




       }catch(Exception e)
       {
           javax.swing.JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         if(indiceCombo==indiceComboUltimo-1)
        {
            JOptionPane.showMessageDialog(null,"Este é o ultimo registro");
        }else
        {
            jCfornecedor.setSelectedIndex(indiceCombo+1);
            indiceCombo = jCfornecedor.getSelectedIndex();
        }  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          if(indiceCombo==0)
        {
            JOptionPane.showMessageDialog(null,"Este é o primeiro registro");
        }else
        {
            jCfornecedor.setSelectedIndex(indiceCombo-1);
            indiceCombo = jCfornecedor.getSelectedIndex();
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      jCfornecedor.setSelectedIndex(0);
       indiceCombo = jCfornecedor.getSelectedIndex();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       jCfornecedor.setSelectedIndex(indiceComboUltimo-1);
        indiceCombo = jCfornecedor.getSelectedIndex();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jCfornecedor.setSelectedItem(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1)));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTnumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnumeroKeyReleased
         
    }//GEN-LAST:event_jTnumeroKeyReleased

    private void jTnumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnumeroKeyPressed
       jTnumero.addKeyListener(new ToolNumericKeyAdapter(10, false));  
    }//GEN-LAST:event_jTnumeroKeyPressed

    private void jTInscEstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTInscEstKeyPressed
           jTInscEst.addKeyListener(new ToolNumericKeyAdapter(30, false));  
    }//GEN-LAST:event_jTInscEstKeyPressed

    private void jTinscMunKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTinscMunKeyPressed
       jTinscMun.addKeyListener(new ToolNumericKeyAdapter(30, false));
    }//GEN-LAST:event_jTinscMunKeyPressed

    private void jTtelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtelKeyPressed
        jTtel.addKeyListener(new ToolNumericKeyAdapter(20, false));
    }//GEN-LAST:event_jTtelKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jCestado;
    private javax.swing.JComboBox jCfornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTInscEst;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTbairro;
    private javax.swing.JTextField jTcidade;
    private javax.swing.JTextField jTcnpj;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTcomplemento;
    private javax.swing.JTextField jTemail;
    private javax.swing.JTextField jTendereco;
    private javax.swing.JTextField jTinscMun;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTnumero;
    private javax.swing.JTextField jTpesquisa;
    private javax.swing.JTextField jTtel;
    // End of variables declaration//GEN-END:variables

    public void mostraDados()
    {
        try
        {

            jTemail.setText(con.getRs().getString("email"));
            jTendereco.setText(con.getRs().getString("endereco"));
            jTnome.setText(con.getRs().getString("nome_fornecedor"));
            jTtel.setText(con.getRs().getString("telefone"));
            jTcodigo.setText(con.getRs().getString("codFornecedor"));
            jTcnpj.setText(con.getRs().getString("cnpj"));
            jTcomplemento.setText(con.getRs().getString("complemento"));
            jCestado.setSelectedItem(con.getRs().getString("estado"));
            jTinscMun.setText(con.getRs().getString("inscmun"));
            jTInscEst.setText(con.getRs().getString("inscest"));
            jTnumero.setText(con.getRs().getString("numero"));
            jTcidade.setText(con.getRs().getString("cidade"));
            jTbairro.setText(con.getRs().getString("bairro"));


         
           /*con.executeStatement("select * from cidade where codCidade = "+jTcidade.getText()+ "order by nome_cidade");
           //con.getRs().first();

           jCcidade.setSelectedItem(con.getRs().getString("nome_cidade"));
           //con.getRs().close();
       
          
           con.executeStatement("select * from fornecedor order by "+ordem);
           con.getRs().first();*/
        }catch(Exception e)
        {
            if (navegar ==1)
                JOptionPane.showMessageDialog(null,"Você ja esta no primeiro item!!!");
             else if(navegar ==2)
             {
                    JOptionPane.showMessageDialog(null,"Você ja esta no ultimo item!!!");
                    try
                    {
                       con.getRs().previous(); 
                    }catch(SQLException erro)
                    {
                        JOptionPane.showMessageDialog(null,erro);
                    }
                    
             }
            else
           // JOptionPane.showMessageDialog(null, ero);
           navegar = 0;
                //JOptionPane.showMessageDialog(null,"mostradas:   "+ e);
        }
        
    }

    public void atualizaFornecedor()
    {
        try
        {
            con.conecta();
            indiceComboUltimo=0;
            jCfornecedor.removeAllItems();
            con.executeStatement("select * from fornecedor order by "+ordem);
            while(con.getRs().next())
            {
                jCfornecedor.addItem(con.getRs().getString("nome_fornecedor"));
                indiceComboUltimo++;
            }
           
            indiceCombo = jCfornecedor.getSelectedIndex();
          
        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
        
    }

     
     private void preenchejTable(String filtro)
    {
         DefaultTableModel modelo2 = (DefaultTableModel) jTable1.getModel();
         modelo2.setRowCount(0);
         
         try
         {
              con.executeStatement("select * from fornecedor f "
                      + " where nome_fornecedor like '%"+filtro+"%'order by "+ordem);
              while(con.getRs().next())
              {
                   jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer()
                  {  
                        public Component getTableCellRendererComponent(JTable table, Object value,  
                        boolean isSelected, boolean hasFocus, int row, int column)
                        {  
                            super.getTableCellRendererComponent(table, value, isSelected,  
                                hasFocus, row, column); 
                           
                            if (row%2==0) {  
                                setBackground(Color.CYAN); 
                                
                            }else if (row%2 == 1) {  
                                setBackground(null); 
                            }
                             
                             return this;  
                        }  
                    });  
                  
                  
                  modelo2.addRow(new Object[]{con.getRs().getString("codFornecedor"),con.getRs().getString("nome_fornecedor")
                  ,con.getRs().getString("telefone"),con.getRs().getString("cidade"),con.getRs().getString("endereco")
                  ,con.getRs().getString("cnpj")});
              }
             
         }catch(Exception e)
         {
             
         }
        
    }
     


}
