/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFLivros.java
 *
 * Created on 8/Out/2011, 22:55:22
 */

package br.classesprincipais;

import br.utilitario.Conexao;
import br.utilitario.Data;
import br.utilitario.Util;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author M4RCO5
 */
public class JFLivros extends javax.swing.JFrame {

    private String ordem ="titulo";
    private int indiceCombo =0;
    private int indiceComboUltimo=0;
    private Conexao con = new Conexao();
    private Util util = new Util();
    public JFLivros() {
        initComponents();
         setLocationRelativeTo(null);
         atualiza();
         atualizaAutor();
         atualizaCategoria();
         atualizaEditora();
         jTcodigo.setEditable(false);
         jTautor.setEditable(false);
         jTeditora.setEditable(false);
         jTcat.setEditable(false);
    }

    public JFLivros(String codigo)
    {
        initComponents();
        atualiza();
         atualizaAutor();
         atualizaCategoria();
         atualizaEditora();

         jTcodigo.setEditable(false);
         jTautor.setEditable(false);
         jTeditora.setEditable(false);
         jTcat.setEditable(false);

         setLocationRelativeTo(null);
        try
        {
            con.conecta();
            con.executeStatement("select * from livro inner join autor on livro.autor_CodAutor = autor.codAutor"+
                  " inner join categoria on livro.categoria_CodCategoria = categoria.codCategoria inner join"+
                  " editora on livro.editora_CodEditora = editora.CodEditora where codLivro =  "+codigo);
            con.getRs().next();
            
            jTano.setText(con.getRs().getString("data_lanc"));
            jTautor.setText(con.getRs().getString("autor_CodAutor"));
            jTcat.setText(con.getRs().getString("categoria_CodCategoria"));
            jTeditora.setText(con.getRs().getString("editora_CodEditora"));
            jTestoqueatual.setText(con.getRs().getString("estoque_atual"));
            jTestoqueminimo.setText(con.getRs().getString("estoque_minimo"));
            jTtitulo.setText(con.getRs().getString("titulo"));
            jTresenha.setText(con.getRs().getString("resenha"));
            jTprecoCusto.setText(con.getRs().getString("preco_custo"));
            jTresenha.setText(con.getRs().getString("resenha"));
            jTprecoVenda.setText(con.getRs().getString("preco_venda"));
            jTcodigo.setText(con.getRs().getString("codLivro"));
            jTIsbn.setText(con.getRs().getString("isbn"));
 
            at();
         
            
        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Erro: "+e);
        }


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTtitulo = new javax.swing.JTextField();
        jTeditora = new javax.swing.JTextField();
        jTano = new javax.swing.JTextField();
        jTcat = new javax.swing.JTextField();
        jTprecoCusto = new javax.swing.JTextField();
        jTprecoVenda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTestoqueatual = new javax.swing.JTextField();
        jTestoqueminimo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTresenha = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jTautor = new javax.swing.JTextField();
        jClivros = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jCeditora = new javax.swing.JComboBox();
        jCautor = new javax.swing.JComboBox();
        jCcategoria = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTfoto = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLfoto = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTIsbn = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setTitle("Gerenciamento de livros");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerenciamento de Livros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Titulo.:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Editora.:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data de Lançamento.:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Preço de Custo.:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Preço de Venda.:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Categoria.:");

        jTano.setMaximumSize(new java.awt.Dimension(1, 1));
        jTano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTanoKeyPressed(evt);
            }
        });

        jTprecoCusto.setFont(new java.awt.Font("Tahoma", 0, 18));
        jTprecoCusto.setNextFocusableComponent(jTprecoVenda);
        jTprecoCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTprecoCustoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTprecoCustoKeyReleased(evt);
            }
        });

        jTprecoVenda.setFont(new java.awt.Font("Tahoma", 0, 18));
        jTprecoVenda.setNextFocusableComponent(jTestoqueatual);
        jTprecoVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTprecoVendaKeyPressed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estoque Atual.:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estoque Minimo.:");

        jTestoqueatual.setFont(new java.awt.Font("Tahoma", 0, 18));
        jTestoqueatual.setNextFocusableComponent(jTestoqueminimo);
        jTestoqueatual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTestoqueatualKeyPressed(evt);
            }
        });

        jTestoqueminimo.setFont(new java.awt.Font("Tahoma", 0, 18));
        jTestoqueminimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTestoqueminimoKeyPressed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Resenha do Livro:");

        jTresenha.setColumns(20);
        jTresenha.setRows(5);
        jTresenha.setNextFocusableComponent(jTprecoCusto);
        jScrollPane1.setViewportView(jTresenha);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Autor.:");

        jClivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClivrosActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Todos livros.:");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordenação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jRadioButton1.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Título");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Data lançamento");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Código");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Código.: ");

        jTcodigo.setBackground(new java.awt.Color(255, 255, 153));

        jCeditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCeditoraActionPerformed(evt);
            }
        });

        jCautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCautorActionPerformed(evt);
            }
        });

        jCcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcategoriaActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("dd/mm/aaaa");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Foto.:");

        jTfoto.setNextFocusableComponent(jTresenha);

        jButton6.setText("...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/Save.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/delete2.JPG"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/Split.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/porta.gif"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/url_add.jpeg"))); // NOI18N
        jButton3.setToolTipText("Cadastro de Autor,Editora e Categoria");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setText("<<");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("<");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText(">");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText(">>");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/print_icon.gif"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9)
                        .addGap(10, 10, 10)
                        .addComponent(jButton10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton11, jButton2, jButton3, jButton4, jButton5});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton10, jButton7, jButton8, jButton9});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7)
                        .addComponent(jButton8))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton10)
                        .addComponent(jButton9)))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(2, 2, 2))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButton3, jButton4, jButton5});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagem"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLfoto, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton12.setText("Imprimir Todos");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ISBN.:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addContainerGap(834, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(448, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTeditora, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTautor, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTano, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addComponent(jTIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jClivros, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTcat, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCcategoria, javax.swing.GroupLayout.Alignment.TRAILING, 0, 375, Short.MAX_VALUE)
                                    .addComponent(jCautor, javax.swing.GroupLayout.Alignment.TRAILING, 0, 375, Short.MAX_VALUE)
                                    .addComponent(jCeditora, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTprecoVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTprecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTestoqueminimo, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTestoqueatual, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                        .addGap(119, 119, 119))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(549, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTestoqueatual, jTestoqueminimo, jTprecoCusto, jTprecoVenda});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTautor, jTcat, jTeditora});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jClivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTeditora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCeditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jTfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTprecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTprecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTestoqueatual, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTestoqueminimo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTestoqueatual, jTestoqueminimo, jTprecoCusto, jTprecoVenda});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTautor, jTcat});

        jMenu1.setText("Sistema");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        Data d = new Data();
        String data = d.convertedata(jTano.getText());
        try
       {
           //Data d = new Data();
           //String data = d.convertedata(jTano.getText());
           if(!jTcodigo.getText().equalsIgnoreCase(""))
           {
              con.conecta();
              con.executaSql("update livro set titulo = ?,editora_CodEditora = ?,data_lanc = ?,preco_custo = ? ,preco_venda = ?,"
                       + "categoria_CodCategoria = ?,estoque_atual = ?,estoque_minimo = ?,resenha = ?,autor_CodAutor = ?,isbn=?, foto =? where codLivro =  "+jTcodigo.getText());

               con.getPs().setString(1,jTtitulo.getText());
               con.getPs().setString(2,jTeditora.getText());
               con.getPs().setString(3,jTano.getText());
               con.getPs().setString(4,jTprecoCusto.getText());
               con.getPs().setString(5,jTprecoVenda.getText());
               con.getPs().setString(6,jTcat.getText());
               con.getPs().setString(7,jTestoqueatual.getText());
               con.getPs().setString(8,jTestoqueminimo.getText());
               con.getPs().setString(9,jTresenha.getText());
               con.getPs().setString(10,jTautor.getText());
               con.getPs().setString(11,jTIsbn.getText());
               con.getPs().setString(12,jTfoto.getText());

               con.getPs().execute();

               javax.swing.JOptionPane.showMessageDialog(null,"Alterado com sucesso !");
               atualiza();


           }else
           {
               con.conecta();
               con.executaSql("insert into livro (titulo,editora_CodEditora,data_lanc,preco_custo,preco_venda,"
                       + "categoria_CodCategoria,estoque_atual,estoque_minimo,resenha,autor_CodAutor,qtde_vendido,foto,isbn) values (?,?,?,?,?,?,?,?,?,?,?,?,?)");

               con.getPs().setString(1,jTtitulo.getText());
               con.getPs().setString(2,jTeditora.getText());
               con.getPs().setString(3,data);
               con.getPs().setString(4,jTprecoCusto.getText());
               con.getPs().setString(5,jTprecoVenda.getText());
               con.getPs().setString(6,jTcat.getText());
               con.getPs().setString(7,jTestoqueatual.getText());
               con.getPs().setString(8,jTestoqueminimo.getText());
               con.getPs().setString(9,jTresenha.getText());
               con.getPs().setString(10,jTautor.getText());
               con.getPs().setString(11,"0");
               con.getPs().setString(12,jTfoto.getText());
               con.getPs().setString(13,jTIsbn.getText());

               con.getPs().execute();

               atualiza();
               javax.swing.JOptionPane.showMessageDialog(null,"Salvo com sucesso");
               limpaCampos();

           }
           
       }catch(Exception e)
       {
           javax.swing.JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpaCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jClivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClivrosActionPerformed
        try
        {
          boolean achei = false;
          con.conecta();
          con.executeStatement("select * from livro order by "+ordem);
          con.getRs().first();
          while(achei==false)
          {
              if(con.getRs().getString("titulo").equals(jClivros.getSelectedItem()))
              {
                  achei=true;
              }else
              {
                  con.getRs().next();
              }
          }
          MostraDados();
          indiceCombo = jClivros.getSelectedIndex();
      }catch( Exception e)
      {
        //javax.swing.JOptionPane.showMessageDialog(null, e);
      }
 
    }//GEN-LAST:event_jClivrosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try
        {
          con.conecta();
          int i = JOptionPane.showConfirmDialog(null, "Deseja excluir o livro "+jClivros.getSelectedItem()+" ?");
          if(i==0)
          {
              con.executaSql("delete from livro where codLivro = ? ");
              con.getPs().setString(1,jTcodigo.getText()) ;
              con.getPs().execute();

              atualiza();
              javax.swing.JOptionPane.showMessageDialog(null, "Deletado com sucesso!");

          }
          

      }catch( Exception e)
      {
          javax.swing.JOptionPane.showMessageDialog(null, e);
      }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
       ordem ="titulo";
       atualiza();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       ordem = "data_lanc";
       atualiza();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
      ordem = "codLivro";
      atualiza();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jCeditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCeditoraActionPerformed
   try
       {
           con.conecta();
           boolean achei =false;
           con.executeStatement("select * from editora order by nome_editora ");
           con.getRs().first();
           while(achei==false)
           {
               if(con.getRs().getString("nome_editora").equals(jCeditora.getSelectedItem()))
               {
                   achei = true;
               }else
               {
                   con.getRs().next();
               }
           }

           jTeditora.setText(con.getRs().getString("CodEditora"));

       }catch(Exception e)
       {
         //  javax.swing.JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jCeditoraActionPerformed

    private void jCautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCautorActionPerformed
       try
       {
           con.conecta();
           boolean achei =false;
           con.executeStatement("select * from autor order by nome_autor ");
           con.getRs().first();
           while(achei==false)
           {
               if(con.getRs().getString("nome_autor").equals(jCautor.getSelectedItem()))
               {
                   achei = true;
               }else
               {
                   con.getRs().next();
               }
           }

           jTautor.setText(con.getRs().getString("codAutor"));

       }catch(Exception e)
       {
         //  javax.swing.JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jCautorActionPerformed

    private void jCcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcategoriaActionPerformed
       try
       {
           con.conecta();
           boolean achei =false;
           con.executeStatement("select * from categoria order by nome_categoria ");
           con.getRs().first();
           while(achei==false)
           {
               if(con.getRs().getString("nome_categoria").equals(jCcategoria.getSelectedItem()))
               {
                   achei = true;
               }else
               {
                   con.getRs().next();
               }
           }

           jTcat.setText(con.getRs().getString("codCategoria"));

       }catch(Exception e)
       {
         //  javax.swing.JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jCcategoriaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFCadastros aux = new JFCadastros();
        aux.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       try
       {
             
            JFileChooser busca_foto = new JFileChooser();
            busca_foto.setCurrentDirectory(new File("src/br/imagens"));
            busca_foto.setDialogTitle("Carrega imagem");
            busca_foto.showOpenDialog(this);
            jLfoto.setIcon(new ImageIcon("src/br/imagens/"+busca_foto.getSelectedFile().getName()));
            jTfoto.setText(busca_foto.getSelectedFile().getName());
            //  busca_foto.showDialog(null, "Salvar");


           
       }catch(Exception e)
       {
           //JOptionPane.showMessageDialog(null, e,"Nao foi possivel carrear",2);
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        con.fechaConexao();
    }//GEN-LAST:event_formWindowClosing

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(indiceCombo==indiceComboUltimo-1)
        {
            JOptionPane.showMessageDialog(null,"Este é o ultimo registro");
        }else
        {
            jClivros.setSelectedIndex(indiceCombo+1);
            indiceCombo = jClivros.getSelectedIndex();
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jClivros.setSelectedIndex(indiceComboUltimo-1);
        indiceCombo = jClivros.getSelectedIndex();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(indiceCombo==0)
        {
            JOptionPane.showMessageDialog(null,"Este é o primeiro registro");
        }else
        {
            jClivros.setSelectedIndex(indiceCombo-1);
            indiceCombo = jClivros.getSelectedIndex();
        }
        
     
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       jClivros.setSelectedIndex(0);
       indiceCombo = jClivros.getSelectedIndex();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       ImprimeLivros imprime = new ImprimeLivros(jTcodigo.getText());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
     ImprimeLivros imprime = new ImprimeLivros();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTprecoCustoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTprecoCustoKeyPressed
       jTprecoCusto.setText(util.verificaNumeros(evt, jTprecoCusto.getText()));
    }//GEN-LAST:event_jTprecoCustoKeyPressed

    private void jTprecoCustoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTprecoCustoKeyReleased

    }//GEN-LAST:event_jTprecoCustoKeyReleased

    private void jTestoqueminimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTestoqueminimoKeyPressed
     
      jTestoqueminimo.setText(util.verificaNumeros(evt, jTestoqueminimo.getText()));     
    }//GEN-LAST:event_jTestoqueminimoKeyPressed

    private void jTprecoVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTprecoVendaKeyPressed
      jTprecoVenda.setText(util.verificaNumeros(evt, jTprecoVenda.getText()));
    }//GEN-LAST:event_jTprecoVendaKeyPressed

    private void jTestoqueatualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTestoqueatualKeyPressed
      jTestoqueatual.setText(util.verificaNumeros(evt, jTestoqueatual.getText()));
    }//GEN-LAST:event_jTestoqueatualKeyPressed

    private void jTanoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTanoKeyPressed
       
        Util util = new Util();
        jTano.setText(util.verificaNumeros(evt,jTano.getText()));
        
        String aux=jTano.getText();
        
        if(jTano.getText().length()==2)
       {
           jTano.setText(aux+"/");
       }
        if(jTano.getText().length()==5)
       {
           jTano.setText(aux+"/");
       }
    }//GEN-LAST:event_jTanoKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jCautor;
    private javax.swing.JComboBox jCcategoria;
    private javax.swing.JComboBox jCeditora;
    private javax.swing.JComboBox jClivros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLfoto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTIsbn;
    private javax.swing.JTextField jTano;
    private javax.swing.JTextField jTautor;
    private javax.swing.JTextField jTcat;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTeditora;
    private javax.swing.JTextField jTestoqueatual;
    private javax.swing.JTextField jTestoqueminimo;
    private javax.swing.JTextField jTfoto;
    private javax.swing.JTextField jTprecoCusto;
    private javax.swing.JTextField jTprecoVenda;
    private javax.swing.JTextArea jTresenha;
    private javax.swing.JTextField jTtitulo;
    // End of variables declaration//GEN-END:variables

    public void limpaCampos()
    {
           jTtitulo.setText("");
            jTeditora.setText("");
            jTano.setText("");
            jTprecoCusto.setText("0");
            jTprecoVenda.setText("0");
            jTcat.setText("");
            jTestoqueatual.setText("0");
            jTestoqueminimo.setText("0");
            jTresenha.setText("");
            jTcodigo.setText("");
            jTautor.setText("");
            jTfoto.setText("");
            jLfoto.setText("");
            jLfoto.setIcon(null);
            jTIsbn.setText("");
    }
    public void MostraDados()
    {
        try
        {

            jTano.setText(con.getRs().getString("data_lanc"));
            jTautor.setText(con.getRs().getString("autor_CodAutor"));
            jTcat.setText(con.getRs().getString("categoria_CodCategoria"));
            jTeditora.setText(con.getRs().getString("editora_CodEditora"));
            jTestoqueatual.setText(con.getRs().getString("estoque_atual"));
            jTestoqueminimo.setText(con.getRs().getString("estoque_minimo"));
            jTtitulo.setText(con.getRs().getString("titulo"));
            jTresenha.setText(con.getRs().getString("resenha"));
            jTprecoCusto.setText(con.getRs().getString("preco_custo"));
            jTresenha.setText(con.getRs().getString("resenha"));
            jTprecoVenda.setText(con.getRs().getString("preco_venda"));
            jTcodigo.setText(con.getRs().getString("codLivro"));
            jTfoto.setText(con.getRs().getString("foto"));
             jLfoto.setIcon(new ImageIcon("src/br/imagens/"+jTfoto.getText()));
            jTIsbn.setText(con.getRs().getString("isbn"));
            
            con.conecta();
            con.executeStatement("select * from editora where CodEditora  = "+jTeditora.getText());
            con.getRs().next();
            jCeditora.setSelectedItem(con.getRs().getString("nome_editora"));

            con.executeStatement("select * from autor where codAutor  = "+jTautor.getText());
            con.getRs().next();
            jCautor.setSelectedItem(con.getRs().getString("nome_autor"));

            con.executeStatement("select * from categoria where codCategoria  = "+jTcat.getText());
            con.getRs().next();
            jCcategoria.setSelectedItem(con.getRs().getString("nome_categoria"));
            

            con.executeStatement("select * from livro order by "+ordem);
            con.getRs().first();

           
        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
        
    }

    public void atualiza()
    {
        try
        {
            indiceComboUltimo=0;
            jClivros.removeAllItems();
            con.conecta();
            con.executeStatement("select titulo from livro order by "+ordem);
            while(con.getRs().next())
            {
                jClivros.addItem(con.getRs().getString("titulo"));
                indiceComboUltimo++;
            }
            indiceCombo = jClivros.getSelectedIndex();
        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }

      public void atualizaAutor()
    {
        try
        {
            jCautor.removeAllItems();
            con.conecta();
            con.executeStatement("select * from autor order by nome_autor");
            while(con.getRs().next())
            {
                jCautor.addItem(con.getRs().getString("nome_autor"));
            }

        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }

        public final void atualizaEditora()
    {
        try
        {
            jCeditora.removeAllItems();
            con.conecta();
            con.executeStatement("select * from editora order by nome_editora");
            while(con.getRs().next())
            {
                jCeditora.addItem(con.getRs().getString("nome_editora"));
            }

        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }

          public void atualizaCategoria()
    {
        try
        {
            jCcategoria.removeAllItems();
            con.conecta();
            con.executeStatement("select * from categoria order by nome_categoria");
            while(con.getRs().next())
            {
                jCcategoria.addItem(con.getRs().getString("nome_categoria"));
            }

        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }

    public void at()
    {
        try
        {
            con.conecta();
            con.executeStatement("select * from editora where CodEditora  = "+jTeditora.getText());
            con.getRs().next();
            jCeditora.setSelectedItem(con.getRs().getString("nome_editora"));


            con.executeStatement("select * from autor where codAutor  = "+jTautor.getText());
            con.getRs().next();
            jCautor.setSelectedItem(con.getRs().getString("nome_autor"));

            con.executeStatement("select * from categoria where codCategoria  = "+jTcat.getText());
            con.getRs().next();
            jCcategoria.setSelectedItem(con.getRs().getString("nome_categoria"));


            con.executeStatement("select * from livro order by "+ordem);
            con.getRs().first();
        }catch(Exception e)
        {

        }
           

    }
}
