/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFLivros.java
 *
 * Created on 8/Out/2011, 22:55:22
 */

package br.classesprincipais;

import br.utilitario.Conexao;
import br.utilitario.Data;
import br.utilitario.ToolNumericKeyAdapter;
 
import br.utilitario.Util;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M4RCO5
 */
public class JFLivros1 extends javax.swing.JFrame {

    private String codEditora="";
    private String codCategoria="";
    private String codAutor="";
    private String ordem ="titulo";
    private int indiceCombo =0;
    private int indiceComboUltimo=0;
    private Conexao con = new Conexao();
    private Util util = new Util();
    private String estoqueatual="";
   
    public JFLivros1() {
         initComponents();
         setLocationRelativeTo(null);
         atualiza();
         atualizaAutor();
         atualizaCategoria();
         atualizaEditora();
         jTcodigo.setEditable(false);
         preenchejTable("");
     
         

    }

    public JFLivros1(String codigo)
    {
        initComponents();
         atualiza();
         atualizaAutor();
         atualizaCategoria();
         atualizaEditora();

         jTcodigo.setEditable(false);

         preenchejTable("");
         setLocationRelativeTo(null);
        try
        {
            con.conecta();
            con.executeStatement("select * from livro inner join autor on livro.autor_CodAutor = autor.codAutor"+
                  " inner join categoria on livro.categoria_CodCategoria = categoria.codCategoria inner join"+
                  " editora on livro.editora_CodEditora = editora.CodEditora where codLivro =  "+codigo);
            con.getRs().next();
            
           // jTano.setText(con.getRs().getString("data_lanc"));
            codAutor = con.getRs().getString("autor_CodAutor");
            codCategoria = con.getRs().getString("categoria_CodCategoria");
            codEditora=con.getRs().getString("editora_CodEditora");
            jTestoqueatual.setText(con.getRs().getString("estoque_atual"));
            jTestoqueminimo.setText(con.getRs().getString("estoque_minimo"));
            jTtitulo.setText(con.getRs().getString("titulo"));
            jTresenha.setText(con.getRs().getString("resenha"));
            jTprecoCusto.setText(con.getRs().getString("preco_custo"));
            jTresenha.setText(con.getRs().getString("resenha"));
            jTprecoVenda.setText(con.getRs().getString("preco_venda"));
            jTcodigo.setText(con.getRs().getString("codLivro"));
            jTIsbn.setText(con.getRs().getString("isbn"));
 
            at();
         
            
        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, "Erro: "+e);
        }


    }
    
    public JFLivros1(String nome,boolean v)
    {
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTtitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTresenha = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jClivros = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jCeditora = new javax.swing.JComboBox();
        jCautor = new javax.swing.JComboBox();
        jCcategoria = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jTfoto = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLfoto = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTIsbn = new javax.swing.JTextField();
        jDateChooserLanc = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTprecoCusto = new JNumberField.JNumberField();
        jTprecoVenda = new JNumberField.JNumberField();
        jTestoqueminimo = new javax.swing.JFormattedTextField();
        jTestoqueatual = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setTitle("Gerenciamento de livros");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerenciamento de Livros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Titulo.:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel2.setText("Editora.:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel3.setText("Data de Lançamento.:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 281, 100, -1));

        jLabel5.setText("Preço de Custo.:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, -1, -1));

        jLabel6.setText("Preço de Venda.:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, -1, -1));

        jLabel7.setText("Categoria.:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel1.add(jTtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 552, -1));

        jLabel4.setText("Estoque Atual.:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, -1, -1));

        jLabel8.setText("Estoque Minimo.:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, -1, -1));

        jLabel9.setText("Resenha do Livro:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jTresenha.setColumns(20);
        jTresenha.setRows(5);
        jTresenha.setNextFocusableComponent(jTprecoCusto);
        jScrollPane1.setViewportView(jTresenha);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 552, 31));

        jLabel10.setText("Autor.:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        jClivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClivrosActionPerformed(evt);
            }
        });
        jPanel1.add(jClivros, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 94, 440, -1));

        jLabel11.setText("Todos livros.:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 97, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordenação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Título");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Data lançamento");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Código");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jRadioButton2)
                .addGap(37, 37, 37)
                .addComponent(jRadioButton3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 36, -1, 51));

        jLabel12.setText("Código.: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jTcodigo.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.add(jTcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 69, -1));

        jCeditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCeditoraActionPerformed(evt);
            }
        });
        jPanel1.add(jCeditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 552, -1));

        jCautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCautorActionPerformed(evt);
            }
        });
        jPanel1.add(jCautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 552, 20));

        jCcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jCcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 552, -1));

        jLabel14.setText("Foto.:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 317, -1, -1));

        jTfoto.setNextFocusableComponent(jTresenha);
        jPanel1.add(jTfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 314, 500, -1));

        jButton6.setText("...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagem"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLfoto, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, -1));

        jButton12.setText("Imprimir Todos");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 93, -1, -1));

        jLabel15.setText("ISBN.:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));
        jPanel1.add(jTIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 320, -1));

        jDateChooserLanc.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(jDateChooserLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 180, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/Save.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 620, 60, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/Split.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 60, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/delete2.JPG"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 60, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/porta.gif"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 60, 45));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/url_add.jpeg"))); // NOI18N
        jButton3.setToolTipText("Cadastro de Autor,Editora e Categoria");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 60, 45));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/print_icon.gif"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 60, -1));

        jButton7.setText("<<");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 70, 30));

        jButton8.setText("<");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 70, 30));

        jButton9.setText(">");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 70, 30));

        jButton10.setText(">>");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 70, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cód", "Titulo", "Quant, Estoque", "Valor"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 930, 150));

        jTprecoCusto.setText("0");
        jTprecoCusto.setToolTipText("");
        jTprecoCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTprecoCustoKeyPressed(evt);
            }
        });
        jPanel1.add(jTprecoCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 90, 30));
        jPanel1.add(jTprecoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 90, 30));

        jTestoqueminimo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTestoqueminimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTestoqueminimoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTestoqueminimoKeyReleased(evt);
            }
        });
        jPanel1.add(jTestoqueminimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 90, 30));

        jTestoqueatual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTestoqueatual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTestoqueatualFocusGained(evt);
            }
        });
        jTestoqueatual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTestoqueatualMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTestoqueatualMouseEntered(evt);
            }
        });
        jTestoqueatual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTestoqueatualKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTestoqueatualKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTestoqueatualKeyTyped(evt);
            }
        });
        jPanel1.add(jTestoqueatual, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 970, 680));

        jMenu1.setText("Sistema");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        Data d = new Data();
       // String data = d.convertedata(jTano.getText());
        try
       {
           if(jTtitulo.getText().equalsIgnoreCase(""))
           {
               JOptionPane.showMessageDialog(null,"É obrigatório preencher o campo Titulo");
           }else
           {
                   //Data d = new Data();
               //String data = d.convertedata(jTano.getText());
               if(!jTcodigo.getText().equalsIgnoreCase(""))
               {
                   java.util.Date pega = jDateChooserLanc.getDate();
                        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
                        String data3  = formato.format(pega);
                        System.out.print(data3);
                        
                  con.conecta();
                  con.executaSql("update livro set titulo = ?,editora_CodEditora = ?,data_lanc = ?,preco_custo = ? ,preco_venda = ?,"
                           + "categoria_CodCategoria = ?,estoque_atual = ?,estoque_minimo = ?,resenha = ?,autor_CodAutor = ?,isbn=?, foto =? where codLivro =  "+jTcodigo.getText());

                   con.getPs().setString(1,jTtitulo.getText());
                   con.getPs().setString(2,codEditora);
                   con.getPs().setString(3,data3);
                   con.getPs().setFloat(4,jTprecoCusto.getValue().floatValue());
                   con.getPs().setFloat(5,jTprecoVenda.getValue().floatValue());
                   con.getPs().setString(6,codCategoria);
                   con.getPs().setString(7,jTestoqueatual.getText());
                   con.getPs().setString(8,jTestoqueminimo.getText());
                   con.getPs().setString(9,jTresenha.getText());
                   con.getPs().setString(10,codAutor);
                   con.getPs().setString(11,jTIsbn.getText());
                   con.getPs().setString(12,jTfoto.getText());

                   con.getPs().execute();

                   javax.swing.JOptionPane.showMessageDialog(null,"Alterado com sucesso !");
                   atualiza();
                   preenchejTable("");


               }else
               {
                   
                       java.util.Date pega = jDateChooserLanc.getDate();
                        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
                        String data3  = formato.format(pega);
                        System.out.print(data3);
                   
                   con.conecta();
                   con.executaSql("insert into livro (titulo,editora_CodEditora,data_lanc,preco_custo,preco_venda,"
                           + "categoria_CodCategoria,estoque_atual,estoque_minimo,resenha,autor_CodAutor,qtde_vendido,foto,isbn) values (?,?,?,?,?,?,?,?,?,?,?,?,?)");

                   con.getPs().setString(1,jTtitulo.getText());
                   con.getPs().setString(2,codEditora);
                   con.getPs().setString(3,data3);
                   con.getPs().setFloat(4,jTprecoCusto.getValue().floatValue());
                   con.getPs().setFloat(5,jTprecoVenda.getValue().floatValue());
                   con.getPs().setString(6,codCategoria);
                   con.getPs().setString(7,jTestoqueatual.getText());
                   con.getPs().setString(8,jTestoqueminimo.getText());
                   con.getPs().setString(9,jTresenha.getText());
                   con.getPs().setString(10,codAutor);
                   con.getPs().setString(11,"0");
                   con.getPs().setString(12,jTfoto.getText());
                   con.getPs().setString(13,jTIsbn.getText());

                   con.getPs().execute();

                   atualiza();
                   javax.swing.JOptionPane.showMessageDialog(null,"Salvo com sucesso");
                   limpaCampos();
                   preenchejTable("");

               }//fim  2 a  a   else

           
           }//fim 1 else
           
       }catch(Exception e)
       {
           javax.swing.JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpaCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jClivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClivrosActionPerformed
        try
        {
          boolean achei = false;
          con.conecta();
          con.executeStatement("select * from livro order by "+ordem);
          con.getRs().first();
          while(achei==false)
          {
              if(con.getRs().getString("titulo").equals(jClivros.getSelectedItem()))
              {
                  achei=true;
              }else
              {
                  con.getRs().next();
              }
          }
          MostraDados();
          indiceCombo = jClivros.getSelectedIndex();
      }catch( Exception e)
      {
        //javax.swing.JOptionPane.showMessageDialog(null, e);
      }
 
    }//GEN-LAST:event_jClivrosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try
        {
          con.conecta();
          int i = JOptionPane.showConfirmDialog(null, "Deseja excluir o livro "+jClivros.getSelectedItem()+" ?");
          if(i==0)
          {
              con.executaSql("delete from livro where codLivro = ? ");
              con.getPs().setString(1,jTcodigo.getText()) ;
              con.getPs().execute();

              atualiza();
              preenchejTable("");
              javax.swing.JOptionPane.showMessageDialog(null, "Deletado com sucesso!");

          }
          

      }catch( Exception e)
      {
          javax.swing.JOptionPane.showMessageDialog(null, e);
      }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
       ordem ="titulo";
       atualiza();
       preenchejTable("");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       ordem = "data_lanc";
       atualiza();
       preenchejTable("");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
      ordem = "codLivro";
      atualiza();
      preenchejTable("");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jCeditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCeditoraActionPerformed
   try
       {
           con.conecta();
           boolean achei =false;
           con.executeStatement("select * from editora order by nome_editora ");
           con.getRs().first();
           while(achei==false)
           {
               if(con.getRs().getString("nome_editora").equals(jCeditora.getSelectedItem()))
               {
                   achei = true;
               }else
               {
                   con.getRs().next();
               }
           }
          codEditora = con.getRs().getString("CodEditora");
          // jTeditora.setText(con.getRs().getString("CodEditora"));

       }catch(Exception e)
       {
         //  javax.swing.JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jCeditoraActionPerformed

    private void jCautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCautorActionPerformed
       try
       {
           con.conecta();
           boolean achei =false;
           con.executeStatement("select * from autor order by nome_autor ");
           con.getRs().first();
           while(achei==false)
           {
               if(con.getRs().getString("nome_autor").equals(jCautor.getSelectedItem()))
               {
                   achei = true;
               }else
               {
                   con.getRs().next();
               }
           }
         codAutor = con.getRs().getString("codAutor");
         //  jTautor.setText(con.getRs().getString("codAutor"));

       }catch(Exception e)
       {
         //  javax.swing.JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jCautorActionPerformed

    private void jCcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcategoriaActionPerformed
       try
       {
           con.conecta();
           boolean achei =false;
           con.executeStatement("select * from categoria order by nome_categoria ");
           con.getRs().first();
           while(achei==false)
           {
               if(con.getRs().getString("nome_categoria").equals(jCcategoria.getSelectedItem()))
               {
                   achei = true;
               }else
               {
                   con.getRs().next();
               }
           }
          codCategoria = con.getRs().getString("codCategoria");
          // jTcat.setText(con.getRs().getString("codCategoria"));

       }catch(Exception e)
       {
         //  javax.swing.JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jCcategoriaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFCadastros aux = new JFCadastros();
        aux.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       try
       {
             
            JFileChooser busca_foto = new JFileChooser();
            busca_foto.setCurrentDirectory(new File("src/br/imagens"));
            busca_foto.setDialogTitle("Carrega imagem");
            busca_foto.showOpenDialog(this);
            jLfoto.setIcon(new ImageIcon("src/br/imagens/"+busca_foto.getSelectedFile().getName()));
            jTfoto.setText(busca_foto.getSelectedFile().getName());
            //  busca_foto.showDialog(null, "Salvar");


           
       }catch(Exception e)
       {
           //JOptionPane.showMessageDialog(null, e,"Nao foi possivel carrear",2);
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        con.fechaConexao();
    }//GEN-LAST:event_formWindowClosing

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(indiceCombo==indiceComboUltimo-1)
        {
            JOptionPane.showMessageDialog(null,"Este é o ultimo registro");
        }else
        {
            jClivros.setSelectedIndex(indiceCombo+1);
            indiceCombo = jClivros.getSelectedIndex();
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jClivros.setSelectedIndex(indiceComboUltimo-1);
        indiceCombo = jClivros.getSelectedIndex();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(indiceCombo==0)
        {
            JOptionPane.showMessageDialog(null,"Este é o primeiro registro");
        }else
        {
            jClivros.setSelectedIndex(indiceCombo-1);
            indiceCombo = jClivros.getSelectedIndex();
        }
        
     
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       jClivros.setSelectedIndex(0);
       indiceCombo = jClivros.getSelectedIndex();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       ImprimeLivros imprime = new ImprimeLivros(jTcodigo.getText());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
     ImprimeLivros imprime = new ImprimeLivros();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTprecoCustoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTprecoCustoKeyPressed
      
    }//GEN-LAST:event_jTprecoCustoKeyPressed

    private void jTestoqueatualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTestoqueatualKeyPressed
   jTestoqueatual.addKeyListener(new ToolNumericKeyAdapter(5, false));             
    }//GEN-LAST:event_jTestoqueatualKeyPressed

    private void jTestoqueatualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTestoqueatualMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTestoqueatualMouseClicked

    private void jTestoqueatualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTestoqueatualMouseEntered
        
    }//GEN-LAST:event_jTestoqueatualMouseEntered

    private void jTestoqueatualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTestoqueatualKeyReleased
               // TODO add your handling code here:
    }//GEN-LAST:event_jTestoqueatualKeyReleased

    private void jTestoqueatualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTestoqueatualKeyTyped
        
    }//GEN-LAST:event_jTestoqueatualKeyTyped

    private void jTestoqueatualFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTestoqueatualFocusGained
       
    }//GEN-LAST:event_jTestoqueatualFocusGained

    private void jTestoqueminimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTestoqueminimoKeyPressed
        jTestoqueminimo.addKeyListener(new ToolNumericKeyAdapter(5, false));          // TODO add your handling code here:
    }//GEN-LAST:event_jTestoqueminimoKeyPressed

    private void jTestoqueminimoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTestoqueminimoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTestoqueminimoKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jClivros.setSelectedItem(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1)));        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLivros1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jCautor;
    private javax.swing.JComboBox jCcategoria;
    private javax.swing.JComboBox jCeditora;
    private javax.swing.JComboBox jClivros;
    private com.toedter.calendar.JDateChooser jDateChooserLanc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLfoto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTIsbn;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTestoqueatual;
    private javax.swing.JFormattedTextField jTestoqueminimo;
    private javax.swing.JTextField jTfoto;
    private JNumberField.JNumberField jTprecoCusto;
    private JNumberField.JNumberField jTprecoVenda;
    private javax.swing.JTextArea jTresenha;
    private javax.swing.JTextField jTtitulo;
    // End of variables declaration//GEN-END:variables

    public void limpaCampos()
    {
           jTtitulo.setText("");
            //jTano.setText("");
            jTprecoCusto.setText("0");
            jTprecoVenda.setText("0");
            jTestoqueatual.setText("0");
            jTestoqueminimo.setText("0");
            jTresenha.setText("");
            jTcodigo.setText("");
            jTfoto.setText("");
            jLfoto.setText("");
            jLfoto.setIcon(null);
            jTIsbn.setText("");
    }
    public void MostraDados()
    {
        try
        {
            

            //((JTextField) jDateChooserLanc.getDateEditor().getUiComponent()).setText(con.getRs().getString("data_lanc"));
            codAutor = con.getRs().getString("autor_CodAutor");
            codCategoria=con.getRs().getString("categoria_CodCategoria");
            codEditora=con.getRs().getString("editora_CodEditora");
            jTestoqueatual.setText(con.getRs().getString("estoque_atual"));
            jTestoqueminimo.setText(con.getRs().getString("estoque_minimo"));
            jTtitulo.setText(con.getRs().getString("titulo"));
            jTresenha.setText(con.getRs().getString("resenha"));
            jTprecoCusto.setText(con.getRs().getString("preco_custo"));
            jTresenha.setText(con.getRs().getString("resenha"));
            jTprecoVenda.setText(con.getRs().getString("preco_venda"));
            jTcodigo.setText(con.getRs().getString("codLivro"));
            jTfoto.setText(con.getRs().getString("foto"));
             jLfoto.setIcon(new ImageIcon("src/br/imagens/"+jTfoto.getText()));
            jTIsbn.setText(con.getRs().getString("isbn"));
            jDateChooserLanc.setDate(con.getRs().getDate("data_lanc"));
            
            con.conecta();
            con.executeStatement("select * from editora where CodEditora  = "+codEditora);
            con.getRs().next();
            jCeditora.setSelectedItem(con.getRs().getString("nome_editora"));

            con.executeStatement("select * from autor where codAutor  = "+codAutor);
            con.getRs().next();
            jCautor.setSelectedItem(con.getRs().getString("nome_autor"));

            con.executeStatement("select * from categoria where codCategoria  = "+codCategoria);
            con.getRs().next();
            jCcategoria.setSelectedItem(con.getRs().getString("nome_categoria"));
            

            con.executeStatement("select * from livro order by "+ordem);
            con.getRs().first();

           
        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
        
    }

    public void atualiza()
    {
        try
        {
            indiceComboUltimo=0;
            jClivros.removeAllItems();
            con.conecta();
            con.executeStatement("select titulo from livro order by "+ordem);
            while(con.getRs().next())
            {
                jClivros.addItem(con.getRs().getString("titulo"));
                indiceComboUltimo++;
            }
            indiceCombo = jClivros.getSelectedIndex();
        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }

      public void atualizaAutor()
    {
        try
        {
            jCautor.removeAllItems();
            con.conecta();
            con.executeStatement("select * from autor order by nome_autor");
            while(con.getRs().next())
            {
                jCautor.addItem(con.getRs().getString("nome_autor"));
            }

        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }

        public final void atualizaEditora()
    {
        try
        {
            jCeditora.removeAllItems();
            con.conecta();
            con.executeStatement("select * from editora order by nome_editora");
            while(con.getRs().next())
            {
                jCeditora.addItem(con.getRs().getString("nome_editora"));
            }

        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }

          public void atualizaCategoria()
    {
        try
        {
            jCcategoria.removeAllItems();
            con.conecta();
            con.executeStatement("select * from categoria order by nome_categoria");
            while(con.getRs().next())
            {
                jCcategoria.addItem(con.getRs().getString("nome_categoria"));
            }

        }catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }

    public void at()
    {
        try
        {
            con.conecta();
            con.executeStatement("select * from editora where CodEditora  = "+codEditora);
            con.getRs().next();
            jCeditora.setSelectedItem(con.getRs().getString("nome_editora"));


            con.executeStatement("select * from autor where codAutor  = "+codAutor);
            con.getRs().next();
            jCautor.setSelectedItem(con.getRs().getString("nome_autor"));

            con.executeStatement("select * from categoria where codCategoria  = "+codCategoria);
            con.getRs().next();
            jCcategoria.setSelectedItem(con.getRs().getString("nome_categoria"));


            con.executeStatement("select * from livro order by "+ordem);
            con.getRs().first();
        }catch(Exception e)
        {

        }
           

    }
    
    private void preenchejTable(String filtro)
    {
         DefaultTableModel modelo2 = (DefaultTableModel) jTable1.getModel();
         modelo2.setRowCount(0);
         
         try
         {
              con.executeStatement("select * from livro l "
                      + " where titulo like '%"+filtro+"%' order by "+ordem);
              while(con.getRs().next())
              {
                   jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer()
                  {  
                        public Component getTableCellRendererComponent(JTable table, Object value,  
                        boolean isSelected, boolean hasFocus, int row, int column)
                        {  
                            super.getTableCellRendererComponent(table, value, isSelected,  
                                hasFocus, row, column); 
                           
                            if (row%2==0) {  
                                setBackground(Color.CYAN); 
                                
                            }else if (row%2 == 1) {  
                                setBackground(null); 
                            }
                             
                             return this;  
                        }  
                    });  
                  
                  
                  modelo2.addRow(new Object[]{con.getRs().getString("codLivro"),con.getRs().getString("titulo")
                  ,con.getRs().getString("estoque_atual"),con.getRs().getString("preco_venda")});
              }
             
         }catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,"err   "+ e);
         }
        
    }
     
    
  
   
}


