/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFVendas.java
 *
 * Created on 8/Out/2011, 22:51:51
 */

package br.classesprincipais;

import br.com.improving.carrinho.CarrinhoCompras;
import br.com.improving.carrinho.Item;
import br.com.improving.carrinho.Produto;
import br.utilitario.Conexao;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import br.utilitario.Data;
import java.awt.Color;
import java.awt.Component;
import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M4RCO5
 */
public final class JFVendas extends javax.swing.JFrame {

    //posiçao do arraylist de codigo do livro
   // private int posCodigo;
    private int posQuant;
    
    private List<Integer> posCodigo = new ArrayList<Integer>();
    
    private int clica=0;
    private int clicado=0;
    private int verifica_rows=0;
    private int cont=0;
    private int cont_total=0;
    private Conexao con = new Conexao();
    private String filtro="titulo";
    private String ordem="titulo";
    private Data dataUtil;
    private Date data = new Date();
    private double valor_total_venda;
    private List<Integer> lista = new ArrayList<Integer>();
    private List<Integer> quantidade = new ArrayList<Integer>();
    private List<Double> valor_unitario = new ArrayList<Double>();
    private List<Double> sub_total = new ArrayList<Double>();
    private double total_venda ;
    private double valorPago = 0; 
    public JFVendas() {
        initComponents();
        setLocationRelativeTo(null);
        atualizaTodos();
        atualizaClientes();

        jTdata.setText(data.getDate()+"/"+dataUtil.retornaMes(data.getMonth()+1)+"/"+(data.getYear()+1900));
        jTdata.setEditable(false);
        jTprecoTotal.setText("0");
        jTjuros.setText("0");
        jTNumParcelas.setText("0");
        jTValorParcela.setText("0");
        jTValorRecebido.setText("0");
        jTdesconto.setText("0");
        jPanelParcelado.setVisible(false);
        jCcliente.grabFocus();
        DefaultTableModel modelo = (DefaultTableModel) jTableDetalhes.getModel();
        modelo.setRowCount(0);
        //jTableDetalhes.setEnabled(false);
       // execProcedure();
       
        jTableDetalhes.getColumnModel().getColumn(0).setMinWidth(40);
        jTableDetalhes.getColumnModel().getColumn(0).setMaxWidth(40);
        jTableDetalhes.getColumnModel().getColumn(1).setMinWidth(300);
        jTableDetalhes.getColumnModel().getColumn(1).setMaxWidth(300);
        jTableDetalhes.getColumnModel().getColumn(2).setMinWidth(40);
        jTableDetalhes.getColumnModel().getColumn(2).setMaxWidth(40);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroupFP = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTdata = new javax.swing.JTextField();
        jTprecoTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTValorRecebido = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jRaVista = new javax.swing.JRadioButton();
        jRParcelado = new javax.swing.JRadioButton();
        jPanelParcelado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTNumParcelas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTjuros = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTValorParcela = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTprime_vencimento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTdesconto = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLcodCli = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jCcliente = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDetalhes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jCtodos = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTpesTitulo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setTitle("Venda de Livros");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Valor total :");

        jLabel16.setText("Data da venda :");

        jLabel6.setText("Valor recebido:");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Formas de Pagamento"));

        buttonGroupFP.add(jRaVista);
        jRaVista.setSelected(true);
        jRaVista.setText("Á Vista");
        jRaVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRaVistaActionPerformed(evt);
            }
        });

        buttonGroupFP.add(jRParcelado);
        jRParcelado.setText("Parcelado");
        jRParcelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRParceladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jRaVista)
                .addGap(10, 10, 10)
                .addComponent(jRParcelado)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRaVista)
                .addComponent(jRParcelado))
        );

        jPanelParcelado.setBorder(javax.swing.BorderFactory.createTitledBorder("Parcelamento"));
        jPanelParcelado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nº parcelas:");
        jPanelParcelado.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 23, -1, -1));

        jTNumParcelas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTNumParcelasFocusLost(evt);
            }
        });
        jPanelParcelado.add(jTNumParcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, -1));

        jLabel4.setText("Juros(%):");
        jPanelParcelado.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 49, -1, -1));

        jTjuros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTjurosFocusLost(evt);
            }
        });
        jPanelParcelado.add(jTjuros, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 60, -1));

        jLabel5.setText("Valor de cada parcela:");
        jPanelParcelado.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jTValorParcela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTValorParcelaFocusGained(evt);
            }
        });
        jPanelParcelado.add(jTValorParcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 71, -1));

        jLabel7.setText("Primeiro vencimento:");
        jPanelParcelado.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));
        jPanelParcelado.add(jTprime_vencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 78, -1));

        jLabel1.setText("Desconto:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanelParcelado, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTdata, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jTValorRecebido, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTprecoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jTdesconto, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTprecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jTdesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelParcelado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 630, 180));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/Salvar.png"))); // NOI18N
        jButton7.setText("    Efetuar venda");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/delete.gif"))); // NOI18N
        jButton8.setText(" Cancelar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/1_copy_32.png"))); // NOI18N
        jButton9.setText("   Nova venda");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/porta.gif"))); // NOI18N
        jButton11.setText("                Sair");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Histórico de vendas");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton8, jButton9});

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        jLcodCli.setText("jLabel17");

        jLabel13.setText("Cliente :");

        jLabel17.setText("Código cliente: ");

        jCcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCclienteActionPerformed(evt);
            }
        });
        jCcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCclienteKeyPressed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/icone_cadastro.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/carregando.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLcodCli))
                    .addComponent(jCcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLcodCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCcliente)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 630, -1));

        jLabel14.setText("Livro(s) : (Selecione um livro para exclui-lo da lista)");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jTableDetalhes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Titulo", "Quant", "Valor Unitário", "Sub Total"
            }
        ));
        jTableDetalhes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDetalhesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDetalhes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 660, 121));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenação"));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Ordem alfabética");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Ano de Lançamento");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)))
        );

        jLabel12.setText("Todos livros cadastrados");

        jCtodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtodosActionPerformed(evt);
            }
        });
        jCtodos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCtodosKeyPressed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/icone_detalhes.gif"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/meu-orcamento.gif"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCtodos, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(6, 6, 6)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton3, jButton6});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jCtodos))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 670, 100));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 740, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 740, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 740, 10));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        jLabel2.setText("Pesquisa:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jTpesTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTpesTituloKeyReleased(evt);
            }
        });
        getContentPane().add(jTpesTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 400, 30));

        jMenu1.setText("Sistema");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFCliente aux;
        try {
            aux = new JFCliente();
             aux.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(JFVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCclienteActionPerformed
       try
        {
            con.conecta();
            boolean achei=false;
            con.executeStatement("select nome_cliente,codCliente from view_cliente ");
            con.getRs().first() ;
           
            while(achei==false)
            {
                if(con.getRs().getString("nome_cliente").equalsIgnoreCase((String)jCcliente.getSelectedItem()))
                {
                    achei=true;break;
                }else
                {
                    con.getRs().next();
                }
                
            }

            jLcodCli.setText(con.getRs().getString("codCliente"));
       

        }catch(Exception e)
        {
             //javax.swing.JOptionPane.showMessageDialog(null,"Combobox do cliente " +e);
        }
    }//GEN-LAST:event_jCclienteActionPerformed

    private void jRParceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRParceladoActionPerformed
        jTNumParcelas.setText("2");
        jPanelParcelado.setVisible(true);
        jTNumParcelas.grabFocus();
    }//GEN-LAST:event_jRParceladoActionPerformed

    private void jRaVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRaVistaActionPerformed
        jPanelParcelado.setVisible(false);
    }//GEN-LAST:event_jRaVistaActionPerformed

    private void jTValorParcelaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTValorParcelaFocusGained
        atualizaValorParcelas();
    }//GEN-LAST:event_jTValorParcelaFocusGained

    private void jTNumParcelasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTNumParcelasFocusLost
        atualizaValorParcelas();
    }//GEN-LAST:event_jTNumParcelasFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
    //atualizaClientes2();       
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         con.fechaConexao();
    }//GEN-LAST:event_formWindowClosing

    private void jTableDetalhesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDetalhesMouseClicked

        try
        {
            int i = JOptionPane.showConfirmDialog(null,"Deseja remover este livro da lista ?","",JOptionPane.YES_NO_CANCEL_OPTION);
            if(i==0)
            {
                double valor=0;
                DefaultTableModel modelo = (DefaultTableModel) jTableDetalhes.getModel();

                int parouaqui=0;
                String x = String.valueOf(jTableDetalhes.getValueAt(jTableDetalhes.getSelectedRow(), 0));
                int codigo = Integer.parseInt(x);
                valor = Double.parseDouble(String.valueOf(jTableDetalhes.getValueAt(jTableDetalhes.getSelectedRow(), 4))); 

                for(int a=0;a<lista.size();a++)
                {
                    if(jTableDetalhes.getValueAt(jTableDetalhes.getSelectedRow(), 0).equals(String.valueOf(lista.get(a))))
                    {
                        System.out.println("\nACHOU " );
                        parouaqui=a;
                    }
                        
                    System.out.println("\nLISTA(CODIGO DOS LIVROS) ANTES: "+lista.get(a));
                    System.out.println("\nQUANTIDADE ANTES: "+quantidade.get(a));
                   //System.out.println("\nLISTA ANTES, INDEXOF: "+lista.indexOf(a));
                   // System.out.println("\nLISTA ANTES, INDEXOF: "+lista.);
                }
               //remove o código do livro que foi selecionado na grid
               lista.remove( lista.indexOf(codigo) );  
               
               //REMOVE DA LISTA QAUNTIDADE 
               quantidade.remove(quantidade.get(parouaqui));
               total_venda-=valor;
               jTprecoTotal.setText(String.valueOf(total_venda));
               
               
               
               for(int a=0;a<lista.size();a++)
                {
                    System.out.println("\nLISTA (CODIGO DOS LIVROS) DEPOIS: "+lista.get(a));
                    System.out.println("\nQUANTIDADE DEPOIS: "+quantidade.get(a));
                }

               //remove a linha selecionada
               ((DefaultTableModel) jTableDetalhes.getModel()).removeRow(jTableDetalhes.getSelectedRow()); 

               //decrementa o contador da quantidade e do codigo do livro
               cont--;
             }

            
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
      
       
    }//GEN-LAST:event_jTableDetalhesMouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        dispose();
}//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String codVenda="";
        valorPago =  Double.parseDouble(jTValorRecebido.getText());
        try {
            if(jTprecoTotal.getText().equalsIgnoreCase("0.0")) {
                JOptionPane.showMessageDialog(null,"Nenhum livro foi adicionado!");
            }else {
                String tipo = "avista";
                
                if(jRaVista.isSelected()) {
                    tipo = "avista";
                }else {
                    tipo ="parcelado";
                }
                
                Data d = new Data();
                String data = d.convertedata(jTdata.getText());
                con.conecta();
                con.executaSql("insert into venda (cliente_CodCliente,data_venda,valor_total,valor_recebido) values (?,?,?,?)");
                con.getPs().setString(1,jLcodCli.getText());
                con.getPs().setString(2,data);
                con.getPs().setString(3,String.valueOf(total_venda));
                con.getPs().setString(4,jTValorRecebido.getText());
                con.getPs().execute();
                
                
                con.executaSql("select ultima from view_ultima_venda");
                con.getRs().next();
                codVenda = con.getRs().getString("ultima");
                
                //insere na tabela forma_pg
           /*con.conecta();
           con.executaSql("insert into forma_pg (tipo,venda_codVenda,NumParcelas) values (?,?,?)");
           con.getPs().setString(1,tipo);
           con.getPs().setString(2,codVenda);
           con.getPs().setString(3,jTNumParcelas.getText());
           con.getPs().execute();*/
                
                
                int nume= 0;
                for(int i =0;i<lista.size();i++) {
                    con.executaSql("select estoque_atual from livro where codLivro = "+lista.get(i));
                    
                    con.getRs().next();
                    
                    nume = Integer.parseInt(con.getRs().getString("estoque_atual"));
                    int aux =0;
                    
                    if(nume>0) {
                        
                        //Stored Pocedure que insere na tabela itens_venda
                        CallableStatement call = con.getCon().prepareCall("call pr_insere_itens_venda('"
                                +codVenda+ "',"
                                + "'"+String.valueOf(lista.get(i))+"',"
                                + "'"+jTprecoTotal.getText()+"',"
                                + "'"+String.valueOf(quantidade.get(i))+"',"
                                + "'"+String.valueOf(valor_unitario.get(i))+"','"+String.valueOf(sub_total.get(i))+"'"
                                + ")");
                        call.execute();
                        
                        
                        //atualiza quantidade de livro comprado pelo cliente*/
                        execProcedureQtdeComprado();
                        
                    /*Após preencher a tablea itens_venda , é disparada a trigger que atualiza
                     o estoque atual do livro*/
                        
                    /*Antes preencher a tablea itens_venda , é disparada a trigger que atualiza
                     a quantidade que o livro foi vendido*/
                        
                        
                    }
                    
                    
                }
                double valorTotal= Double.parseDouble(jTprecoTotal.getText());
                
                //Verifica se o valor pago é igual ou menor que o valor total da compra
                
                if(valorTotal > valorPago) {
               /* double diferenca = (Double.parseDouble(jTprecoTotal.getText()) - Double.parseDouble(jTValorRecebido.getText()));
                System.out.println("Entra no contas a receber !");
                con.conecta();
                con.executaSql("insert into contas_receber (venda_codVenda,valor_receber) values (?,?)");
                con.getPs().setString(1,String.valueOf(codVenda));
                con.getPs().setString(2,String.valueOf(diferenca));
                con.getPs().execute();
                System.out.println("Inseriu no contas a receber !");*/
                }
                
                if(jRParcelado.isSelected()) {
                    con.conecta();
                    con.executaSql("insert into contas_receber (venda_codVenda,situacao) values (?,?)");
                    con.getPs().setString(1,codVenda);
                    con.getPs().setString(2,"aberto");
                    con.getPs().execute();
                    
                    con.executaSql("select max(codContas_receber) as codigo from contas_receber");
                    con.getRs().next();
                    String codcr = con.getRs().getString("codigo");
                    con.getRs().first();
                    
                    int qtd = Integer.parseInt(jTNumParcelas.getText());
                    while(qtd>0) {
                        
                        //Stored Pocedure que insere na tabela parcelas
                        
                        CallableStatement callparcela = con.getCon().prepareCall("call pr_insere_parcelas(?,?,?,?,?)");
                        callparcela.setString(1,codcr);
                        callparcela.setString(2,jTValorParcela.getText());
                        callparcela.setString(3,jTValorRecebido.getText());
                        callparcela.setString(4,jTNumParcelas.getText());
                        callparcela.setString(5,"N");
                        callparcela.execute();
                        
                        qtd--;
                    }
                    
                }
                
                javax.swing.JOptionPane.showMessageDialog(null,"Venda efetuada com sucesso");
                zerarVariaveis();
            }
        }catch(SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null,e);
            jTprecoTotal.setText("0.0");
            
        }
}//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        zerarVariaveis();
        javax.swing.JOptionPane.showMessageDialog(null,"Venda cancelada");
}//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        zerarVariaveis();
}//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        JFVendasFeitas aux = new JFVendasFeitas();
        aux.setVisible(true);
        aux = null;
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jCclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCclienteKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
        {
           
           jCtodos.grabFocus();
            
        } 
    }//GEN-LAST:event_jCclienteKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        adicionaNaLista(jCtodos);
        
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFDetalhes aux =  new JFDetalhes(jCtodos);
        aux.setVisible(true);
}//GEN-LAST:event_jButton3ActionPerformed

    private void jCtodosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCtodosKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER) {
            
            adicionaNaLista(jCtodos);
            
        }
        
        if(evt.getKeyCode() == evt.VK_TAB) {
            jTValorRecebido.grabFocus();
            
        }
}//GEN-LAST:event_jCtodosKeyPressed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        ordem="data_lanc";
        atualizaTodos();
}//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        ordem="titulo";
        atualizaTodos();
}//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTjurosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTjurosFocusLost
       double valorAtual=0,valorFinal=0,juros=0;
       
       valorAtual = Double.parseDouble(jTprecoTotal.getText());
       juros = Double.parseDouble(jTjuros.getText());
       
       valorFinal=(valorAtual+(valorAtual*juros)/100);
       
       jTprecoTotal.setText(String.valueOf(Math.ceil(valorFinal)));
       
    }//GEN-LAST:event_jTjurosFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        atualizaClientes();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTpesTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpesTituloKeyReleased
        try
        {
            String aux = jTpesTitulo.getText();
            
            con.executeStatement("select titulo from livro  where titulo like '%"+aux+"%' ");
              while(con.getRs().next())
              { 
                   jCtodos.setSelectedItem(con.getRs().getString("titulo"));
              }
              
        }catch(Exception e)
        {
            
        }
               // TODO add your handling code here:
    }//GEN-LAST:event_jTpesTituloKeyReleased

    private void jCtodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCtodosActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroupFP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jCcliente;
    private javax.swing.JComboBox jCtodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLcodCli;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelParcelado;
    private javax.swing.JRadioButton jRParcelado;
    private javax.swing.JRadioButton jRaVista;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTNumParcelas;
    private javax.swing.JTextField jTValorParcela;
    private javax.swing.JTextField jTValorRecebido;
    private javax.swing.JTable jTableDetalhes;
    private javax.swing.JTextField jTdata;
    private javax.swing.JTextField jTdesconto;
    private javax.swing.JTextField jTjuros;
    private javax.swing.JTextField jTpesTitulo;
    private javax.swing.JTextField jTprecoTotal;
    private javax.swing.JTextField jTprime_vencimento;
    // End of variables declaration//GEN-END:variables


    public void atualizaValorParcelas()
    {
        double vTotal=0,vCadaParcela=0;
        int numParcelas=0;
        
        numParcelas = Integer.parseInt(jTNumParcelas.getText());
        vTotal = Double.parseDouble(jTprecoTotal.getText());
        vCadaParcela = (vTotal / numParcelas);
        jTValorParcela.setText(String.valueOf(Math.ceil(vCadaParcela)));
    }
    
    public void adicionaNaLista2(JComboBox combo)
    {   
        //TITULO DO LIVRO
        String titulo = (String)combo.getSelectedItem();
        
        //QUANTIDADE
        int quant = Integer.parseInt(JOptionPane.showInputDialog("Informe a quantidade:",1));
         try
            {   
          
                con.executaSql("select titulo,codLivro,preco_venda from livro where titulo =  '"+titulo+"'");
                con.getRs().next();
                
                //CODIGO E PREÇO VENDA(VALOR UNITARIO)
                long codigolivro = Integer.parseInt(con.getRs().getString("codLivro"));
               //BigDecimal preco_venda =0.01;//BigDecimal.valueOf(Double.parseDouble(con.getRs().getString("preco_venda")));
 
               double preco_venda = Double.parseDouble(con.getRs().getString("preco_venda"));
              //  assertEquals(new BigDecimal(123.42).setScale(2, BigDecimal.ROUND_HALF_UP), bigDecimal);
               
                Produto produto = new Produto(codigolivro, titulo);
                Item item = new Item(produto, preco_venda, quant);
                
                CarrinhoCompras carrinho = new CarrinhoCompras();
                carrinho.adicionarItem(produto, preco_venda, quant);
                
                System.out.println("TOTAL:"+carrinho.getValorTotal());
                
            }catch(Exception e)
            {
              javax.swing.JOptionPane.showMessageDialog(null,"erro 1"+ e);
            }
         
         
         
        
    }
    
    public void adicionaNaLista(JComboBox combo)
    {   //Variaveis que serão usadas neste método
        
        //Armazena titulo do livro selecionado
        String titulo = (String)combo.getSelectedItem();
        
        //variavel para recuperar preço dos livros
        double preco = 0,subtotal=0;
        
        //variavel para recuperar o estoque atual do livro
        int estoque_atual=0;
        preco = Double.parseDouble(jTprecoTotal.getText());
        
        //variavel para quantidade de livro informado
        int quant=0;
        int pos=0;
        
        //variavel armazena o total da venda
        double total2=0;
        total2 = Double.parseDouble(jTprecoTotal.getText());
        
        
        try
        {
            quant = Integer.parseInt(JOptionPane.showInputDialog("Informe a quantidade:",1));
            if ((quant != 0) && (quant  > 0)) {
                        quantidade.add(quant);
                        pos=quantidade.size();
                        System.out.println("size do qtd"+pos);
                        System.out.println("cont = "+cont);
            }else
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Valor incorreto");
            }
            
            //Adiciona a quantidade de cada livro e armazena no arraylist
           // quant = Integer.parseInt(JOptionPane.showInputDialog("Informe a quantidade:",1));
           
            
        }catch(Exception e)
        {
             //javax.swing.JOptionPane.showMessageDialog(null,"erro 1"+ e);
        }
        
        try
        {
             
            
            //Verifica o estoque atual do livro
            con.conecta();
            con.executaSql("select estoque_atual from livro where titulo =  '"+titulo+"'");
            con.getRs().next();
            estoque_atual=Integer.parseInt(con.getRs().getString("estoque_atual"));
            
            
            if(estoque_atual <=0)
            {
                JOptionPane.showMessageDialog(null,"Este livro nao está em estoque !");
            }else
            //Verifica se o livro está com estoque
            if(estoque_atual < quantidade.get(cont))
            {
                System.out.println("qtd .get"+quantidade.get(cont));
                
                JOptionPane.showMessageDialog(null,"Esta quantidade nao está  disponivel !\n"
                        + "Este livro possui ( "+estoque_atual+" ) unidades em estoque !");
                
                //deixa  a lista com o valor anterior 
                quantidade.remove(pos-1);
            }else
            {
                con.executaSql("select titulo,codLivro,preco_venda from livro where titulo =  '"+titulo+"'");
                con.getRs().next();
                
                double preco_venda =Double.parseDouble(con.getRs().getString("preco_venda"));
                double sub = preco_venda * quantidade.get(cont);
                double soma=0;
                sub_total.add(sub);
                valor_unitario.add(preco_venda);
                lista.add(Integer.parseInt(con.getRs().getString("codLivro")));
                posCodigo.add(lista.get(cont)); //lista.size();
                
               //  System.out.println("posicao  "+posCodigo.get(cont));
                
                soma=total2+sub;
                jTprecoTotal.setText(String.valueOf(soma));
                total_venda= soma;
               // jTlivros.setText(jTlivros.getText()+(String)combo.getSelectedItem()+" \t "+quant+"\n");
                cont++;
                
                //jtableDetalhes
                try
                {   
                   // con.conecta();

                    DefaultTableModel modelo = (DefaultTableModel) jTableDetalhes.getModel();
                    con.executeStatement("select preco_venda,codLivro,titulo from livro where livro.codLivro = "+lista.get(lista.size()-1));
                    
                    if(verifica_rows==0)
                    {
                       modelo.setRowCount(0); 
                       verifica_rows=1;
                    }
                    
                    
                  

                    while(con.getRs().next())
                    {
                        subtotal = Double.parseDouble(con.getRs().getString("preco_venda"));
                        
                         jTableDetalhes.setDefaultRenderer(Object.class, new DefaultTableCellRenderer()
                        {  
                            public Component getTableCellRendererComponent(JTable table, Object value,  
                            boolean isSelected, boolean hasFocus, int row, int column)
                            {  
                                super.getTableCellRendererComponent(table, value, isSelected,  
                                    hasFocus, row, column); 

                                if (row%2==0) {  
                                    setBackground(Color.LIGHT_GRAY); 

                                }else if (row%2 == 1) {  
                                    setBackground(null); 
                                }

                                 return this;  
                            }  
                      }); 
                        
                        modelo.addRow(new Object[]{con.getRs().getString("codLivro"), con.getRs().getString("titulo"),
                                quant,con.getRs().getString("preco_venda"),(quant * subtotal)
                        });


                    }
                    
                    con.getRs().first();
         

                }catch(SQLException e)
                {
                   javax.swing.JOptionPane.showMessageDialog(null,"adicionando na tabela: "+ e);
                }
            }
            

        }catch(Exception e)
        {
             javax.swing.JOptionPane.showMessageDialog(null,"erro 2"+ e);
        }
        

        
    }
    //Adiciona livros cadastrados no combobox
    public void atualizaTodos()
    {
       try
       {
           jCtodos.removeAllItems();
           con.conecta();
           con.executeStatement("select * from view_titulo_livro order by "+ordem);
           while(con.getRs().next())
           {
               jCtodos.addItem(con.getRs().getString("titulo"));
           }
         
           con.getRs().first();

           

       }catch(SQLException e)
       {
           javax.swing.JOptionPane.showMessageDialog(null, e);
       }
        
    }
    
    //Zerar variaveis
    public void zerarVariaveis()
    {
        try
        {
            quantidade.clear();  
            lista.clear();
          //  jTlivros.setText("");
            jTprecoTotal.setText("0.0");
            jTjuros.setText("0");
            jTNumParcelas.setText("0");
            jTValorParcela.setText("0");
            jTValorRecebido.setText("0");
            jTdesconto.setText("0");
            con.getCon().close();
            valor_unitario.clear();
            sub_total.clear();
            cont=0;
            total_venda=0;
            verifica_rows=0;
            DefaultTableModel modelo = (DefaultTableModel) jTableDetalhes.getModel();
            modelo.setRowCount(0);
            jPanelParcelado.setVisible(false);
            jRaVista.setSelected(true);
            
            
        }catch(Exception e)
        {
            System.out.println(e);
        }
   
    }

    //Atualiza clientes no combobox
    public void atualizaClientes()
    {
       try
       {
           jCcliente.removeAllItems();
           con.conecta();
          
           con.getRs().first();
           con.executeStatement("select nome_cliente from view_cliente  ");
           while(con.getRs().next())
           {
               jCcliente.addItem(con.getRs().getString("nome_cliente"));
           }

           con.getRs().first();
       }catch(Exception e)
       {
           javax.swing.JOptionPane.showMessageDialog(null, e);
       }

    }
    
        public void atualizaClientes2()
    {
       try
       {
           jCcliente.removeAllItems();
           con.conecta();
          
           con.getRs().first();
           con.executeStatement("select codCliente,nome_cliente from view_cliente order by codCliente desc   ");
           while(con.getRs().next())
           {
               jCcliente.addItem(con.getRs().getString("nome_cliente"));
           }

           con.getRs().first();
       }catch(Exception e)
       {
           javax.swing.JOptionPane.showMessageDialog(null, e);
       }

    }

//atualiza qtde de livros comprado pelo cliente
public void execProcedureQtdeComprado()
{
    try
    {
        con.conecta();
        //CallableStatement call = con.getCon().prepareCall("call cadautor(1)");
        CallableStatement call = con.getCon().prepareCall("call qtde_comprado_cliente ()");
        call.execute();

    }catch(SQLException e)
    {
        JOptionPane.showMessageDialog(null,e);
    }
   
}


}
