/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFRelMaisComprou.java
 *
 * Created on 18/Fev/2012, 15:13:09
 */
package br.relatorios;

import br.utilitario.Data;
import java.util.Date;
import javax.swing.JFormattedTextField;
import br.utilitario.Conexao;
import java.text.SimpleDateFormat;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author M4RCO5
 */
public class JFRelLivrosMaisVendidos extends javax.swing.JFrame {

     Date data = new Date();
     String mes="",dia="",ano="";
     private Conexao con = new Conexao();
    // private JFormattedTextField jFde = new JFormattedTextField();
    // private JFormattedTextField jFate = new JFormattedTextField();
    public JFRelLivrosMaisVendidos() {
        initComponents();
        try{
            
           javax.swing.text.MaskFormatter format_textField3 = new javax.swing.text.MaskFormatter("####-##-##");

          // jFde = new javax.swing.JFormattedTextField(format_textField3);
           //jFate = new javax.swing.JFormattedTextField(format_textField3);

        }catch (Exception e){}
       switch(data.getMonth()+1)
       {
           case 1:{mes="01";}break;
           case 2:{mes="02";}break;
           case 3:{mes="03";}break;
           case 4:{mes="04";}break;
           case 5:{mes="05";}break;
           case 6:{mes="06";}break;
           case 7:{mes="07";}break;
           case 8:{mes="08";}break;
           case 9:{mes="09";}break;
           case 10:{mes="10";}break;
           case 11:{mes="11";}break;
           case 12:{mes="12";}break;     
       }
        
      /* jFde.setText((data.getYear()+1900)+"-"+mes+"-"+((data.getDate())-1));
       jFate.setText((data.getYear()+1900)+"-"+mes+"-"+data.getDate());
       //jFate.setText(data.getDate()+"/"+mes+"/"+(data.getYear()+1900));

       jFde.setBounds(50, 45,90,25);
       jFate.setBounds(50,110,90,25);
       jPanel1.add( jFde);
       jPanel1.add(jFate);*/
       
       

        Date date = new Date();
        jTate.setDate(date);


       
       
       setLocationRelativeTo(null);
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTde = new com.toedter.calendar.JDateChooser();
        jTate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setTitle("Relatório Livros Mais Vendidos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informe a data"));

        jLabel1.setText("De :");

        jLabel2.setText("   Até :");

        jTde.setDateFormatString("dd-MM-yyyy");

        jTate.setDate(new java.util.Date(1566779530000L));
        jTate.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTde, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jTde, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Titulo", "Quantidade "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setRowHeight(22);
        jScrollPane1.setViewportView(jTable);

        jButton1.setText("Exibir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/print_icon.gif"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/icones/porta.gif"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("Sistema");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         preenchejTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//       RelMaisVendido imprime = new RelMaisVendido(((JTextField)jTde.getDateEditor().getUiComponent()).getText(),
//               ((JTextField)jTate.getDateEditor().getUiComponent()).getText());
       
        java.util.Date pega = jTde.getDate();
                        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
                        String datade  = formato.format(pega);
                        System.out.print("\n de \n"+datade);
                        
             java.util.Date pega2 = jTate.getDate();
                        SimpleDateFormat formato2 = new SimpleDateFormat("yyyy/MM/dd");
                        String dataate  = formato2.format(pega2);
                        System.out.print("\n ate \n"+dataate);
        
        RelMaisVendido imprime = new RelMaisVendido(datade,dataate);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFRelLivrosMaisVendidos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private com.toedter.calendar.JDateChooser jTate;
    private com.toedter.calendar.JDateChooser jTde;
    // End of variables declaration//GEN-END:variables
    public void preenchejTable()
    {
        try
        {
             java.util.Date pega = jTde.getDate();
                        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
                        String datade  = formato.format(pega);
                        System.out.print("\n de \n"+datade);
                        
             java.util.Date pega2 = jTate.getDate();
                        SimpleDateFormat formato2 = new SimpleDateFormat("yyyy/MM/dd");
                        String dataate  = formato2.format(pega2);
                        System.out.print("\n ate \n"+dataate);
            
            Data data2 = new Data();
            //String de = data.convertedata(jFde.getText());
            //String ate = data.convertedata(jFate.getText());
            con.conecta();
            
            DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();
            con.executeStatement(""+
                   " select livro.codLivro as Codigo, livro.titulo as Titulo , sum(itens_venda.quantidade) as Quantidade  from itens_venda"
                   + " inner join livro on livro.codLivro = itens_venda.livro_codLivro"
                   +" inner join venda on venda.codVenda = itens_venda.venda_CodVenda"
                   +" where venda.data_venda BETWEEN '"+datade+"' and '"+dataate+"' "
                   +" group by livro.titulo order by Quantidade desc ");

            modelo.setRowCount(0);
            
            while(con.getRs().next())
            {
                modelo.addRow(new Object[]{con.getRs().getString("Codigo"),con.getRs().getString("livro.titulo"),con.getRs().getString("Quantidade")
                });


            }
            con.getRs().first();
         

        }catch(Exception e)
        {
           javax.swing.JOptionPane.showMessageDialog(null, e);
        }
        
    }

}
